package gr.mastixa.manager;
import android.app.Activity;
import android.content.Intent;
import android.view.*;
import android.widget.*;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;
public class DashboardUiTest {
    private List<View> views(View v){var out=new ArrayList<View>();out.add(v);if(v instanceof ViewGroup g)for(int n=0;n<g.getChildCount();n++)out.addAll(views(g.getChildAt(n)));return out;}
    private void click(String text){var roots=android.view.inspector.WindowInspector.getGlobalWindowViews();for(int n=roots.size()-1;n>=0;n--)for(var v:views(roots.get(n)))if(v instanceof Button b&&b.getText().toString().equals(text)){b.performClick();return;}fail("Missing button "+text);}
    private void clickContaining(String text){var roots=android.view.inspector.WindowInspector.getGlobalWindowViews();for(int n=roots.size()-1;n>=0;n--)for(var v:views(roots.get(n)))if(v instanceof Button b&&b.getText().toString().contains(text)){b.performClick();return;}fail("Missing button containing "+text);}
    private void invoke(Activity activity,String name,Class<?>[] types,Object...args){try{var m=MainActivity.class.getDeclaredMethod(name,types);m.setAccessible(true);m.invoke(activity,args);}catch(Exception e){throw new RuntimeException(e);}}
    private void screenshot(String file)throws Exception{var i=InstrumentationRegistry.getInstrumentation();Thread.sleep(400);try(var out=new java.io.FileOutputStream(new java.io.File(i.getTargetContext().getExternalFilesDir(null),file))){i.getUiAutomation().takeScreenshot().compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}}
    @Test public void greekDashboardAlertSourceBackAndSavedFilters()throws Exception{var i=InstrumentationRegistry.getInstrumentation();var context=i.getTargetContext();var profile=new ProfileStore.Profile("dashboard-ui","Δοκιμαστικό προφίλ","ui","el");context.deleteDatabase(profile.database());try(var store=new FarmStore(context,profile.database())){store.addField("Χωράφι Α",2);new ActivityStore(store).save(DashboardTest.activity(null,store.fields().get(0).id(),java.time.LocalDate.now().minusDays(1).toString(),"Προγραμματισμένη"));new InventoryStore(store).saveItem(new InventoryStore.Item(null,"Λίπασμα","Εφόδια","kg",5,""));}Activity a=null;try{i.runOnMainSync(()->{UserSession.clear();UserSession.signIn(profile);});a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));var screen=a;i.runOnMainSync(()->click("Πίνακας ελέγχου · Συνολική εικόνα"));i.waitForIdleSync();screenshot("dashboard-ui.png");i.runOnMainSync(()->{invoke(screen,"navigate",new Class[]{String.class},"Ειδοποιήσεις");try{var f=MainActivity.class.getDeclaredField("alertKind");f.setAccessible(true);f.set(screen,"inventory");invoke(screen,"showHome",new Class[]{});}catch(Exception e){throw new RuntimeException(e);}});i.waitForIdleSync();screenshot("alerts-ui.png");i.runOnMainSync(()->clickContaining("Εξαντλημένο απόθεμα"));i.waitForIdleSync();i.runOnMainSync(()->click("‹ Πίσω"));i.waitForIdleSync();i.runOnMainSync(()->{try{var f=MainActivity.class.getDeclaredField("alertKind");f.setAccessible(true);assertEquals("inventory",f.get(screen));}catch(Exception e){throw new RuntimeException(e);}click("Ανανέωση");});i.waitForIdleSync();i.runOnMainSync(()->{var state=new android.os.Bundle();invoke(screen,"onSaveInstanceState",new Class[]{android.os.Bundle.class},state);invoke(screen,"restorePage",new Class[]{android.os.Bundle.class},state.getBundle("current"));invoke(screen,"showHome",new Class[]{});clickContaining("Εξαντλημένο απόθεμα");});i.waitForIdleSync();}finally{var screen=a;i.runOnMainSync(()->{if(screen!=null)screen.finish();UserSession.clear();});}}
    @Test public void backupTimestampChangesOnlyAfterSuccessfulExportAndOnlyForProfile()throws Exception{var i=InstrumentationRegistry.getInstrumentation();var context=i.getTargetContext();var profile=new ProfileStore.Profile("dashboard-backup-ui","Backup test","ui","en");context.deleteDatabase(profile.database());var prefs=context.getSharedPreferences(profile.preferences(),0);prefs.edit().clear().commit();var output=new java.io.File(context.getCacheDir(),"dashboard-backup.json");Activity a=null;try{i.runOnMainSync(()->{UserSession.clear();UserSession.signIn(profile);});a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));var screen=a;i.runOnMainSync(()->{click("Dashboard · Farm overview");invoke(screen,"onActivityResult",new Class[]{int.class,int.class,Intent.class},101,Activity.RESULT_OK,new Intent().setData(android.net.Uri.parse("content://invalid-provider/file")));});i.waitForIdleSync();assertEquals(0,prefs.getLong("last_exported_backup_at",0));i.runOnMainSync(()->click("OK"));i.waitForIdleSync();i.runOnMainSync(()->invoke(screen,"onActivityResult",new Class[]{int.class,int.class,Intent.class},101,Activity.RESULT_OK,new Intent().setData(android.net.Uri.fromFile(output))));i.waitForIdleSync();assertTrue(prefs.getLong("last_exported_backup_at",0)>0);try(var store=new FarmStore(context,profile.database());var in=new java.io.FileInputStream(output)){assertEquals(0,LocalBackup.inspect(store,LocalBackup.read(in)));}i.runOnMainSync(()->click("OK"));i.waitForIdleSync();screenshot("dashboard-en-ui.png");var other=new ProfileStore.Profile("dashboard-other","Other","other","en");assertEquals(0,context.getSharedPreferences(other.preferences(),0).getLong("last_exported_backup_at",0));}finally{var screen=a;i.runOnMainSync(()->{if(screen!=null)screen.finish();UserSession.clear();});prefs.edit().clear().commit();output.delete();}}
}
