package gr.mastixa.manager;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import static org.junit.Assert.*;
import java.time.LocalDate;
import java.io.File;
public class DashboardTest {
    private final android.content.Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    static ActivityStore.Activity activity(String id,String field,String date,String status){return new ActivityStore.Activity(id,date,field,"Πότισμα",status,20,2,"",0,"",0,"","","",0,0,"","Irrigation test","","");}
    @Test public void summaryUsesPostedMoneyOnceAndSeparatesUnitsAndYears()throws Exception{String name="dashboard-totals.db";context.deleteDatabase(name);var recovery=new File(context.getCacheDir(),"dashboard-import.json");try(var store=new FarmStore(context,name);var in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("windows-production.zip")){CatalogImport.apply(store,CatalogImport.read(in),recovery);var c=new CatalogStore(store);String p=c.saveProduct(null,"Oil","L",true);new ProductionStore(store).saveHarvest(new ProductionStore.Harvest(null,"2027-01-01",p,"Oil",store.fields().get(0).id(),8,"",""));byte[] before=LocalBackup.snapshot(store);var s=new DashboardStore(store,true).snapshot("2026",LocalDate.of(2026,9,8));assertEquals(171.5,s.income().doubleValue(),0);assertEquals(60.25,s.expenses().doubleValue(),0);assertEquals(1,s.fields());assertEquals(2.5,s.area(),0);assertEquals(30,s.trees());assertEquals(2,s.products().size());assertEquals(0,s.products().stream().filter(x->x.id().equals(p)).findFirst().orElseThrow().produced(),0);assertEquals(8,s.products().stream().filter(x->x.id().equals(p)).findFirst().orElseThrow().available(),0);assertEquals(14,s.products().stream().filter(x->!x.id().equals(p)).findFirst().orElseThrow().available(),0);assertArrayEquals(before,LocalBackup.snapshot(store));}finally{context.deleteDatabase(name);recovery.delete();}}
    @Test public void scheduledBoundariesCompletionFiltersAndReadOnlyRefresh()throws Exception{String name="dashboard-activities.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){store.addField("Field A",1);String f=store.fields().get(0).id();var a=new ActivityStore(store);var today=LocalDate.of(2026,9,8);String overdue=a.save(activity(null,f,today.minusDays(1).toString(),"Προγραμματισμένη"));a.save(activity(null,f,today.toString(),"Προγραμματισμένη"));a.save(activity(null,f,today.plusDays(7).toString(),"Προγραμματισμένη"));a.save(activity(null,f,today.plusDays(8).toString(),"Προγραμματισμένη"));a.save(activity(null,f,today.toString(),"Ακυρώθηκε"));var d=new DashboardStore(store,true);var alerts=d.alerts(today);assertEquals(3,alerts.size());assertEquals(0,alerts.get(0).severity());assertEquals(1,DashboardStore.filter(alerts,"activity",1,"field a").size());assertTrue(DashboardStore.filter(alerts,"inventory",-1,"").isEmpty());byte[] before=LocalBackup.snapshot(store);assertEquals(alerts,d.alerts(today));assertArrayEquals(before,LocalBackup.snapshot(store));a.save(activity(overdue,f,today.minusDays(1).toString(),"Ολοκληρώθηκε"));assertEquals(2,d.alerts(today).size());assertEquals(3,d.alerts(today.plusDays(1)).size());}finally{context.deleteDatabase(name);}}
    @Test public void stockThresholdsAndDeletedItems()throws Exception{String name="dashboard-stock.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){var stock=new InventoryStore(store);String low=stock.saveItem(new InventoryStore.Item(null,"Low","Supplies","kg",5,""));String empty=stock.saveItem(new InventoryStore.Item(null,"Empty","Supplies","L",0,""));String removed=stock.saveItem(new InventoryStore.Item(null,"Removed","Supplies","kg",0,""));stock.deleteItem(removed);stock.saveMovement(new InventoryStore.Movement(null,low,"2026-01-01","Παραλαβή",5,"","","",0,0,"","","","",""));var d=new DashboardStore(store,true);var alerts=d.alerts(LocalDate.of(2026,9,8));assertEquals(2,alerts.size());assertEquals(empty,alerts.get(0).recordId());assertEquals(1,alerts.get(1).severity());stock.saveMovement(new InventoryStore.Movement(null,low,"2026-01-02","Παραλαβή",1,"","","",0,0,"","","","",""));assertEquals(1,d.alerts(LocalDate.of(2026,9,8)).size());}finally{context.deleteDatabase(name);}}
    @Test public void serviceBoundariesStatusesAndProtectionExpiry()throws Exception{String name="dashboard-service.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){store.addField("Field",1);String f=store.fields().get(0).id();var w=new WorkStore(store);var today=LocalDate.of(2026,9,8);String e=w.saveEquipment(new WorkStore.Equipment(null,"Tractor","","","","","","hours",100,"Ενεργό","",""));String service=w.saveService(new WorkStore.Service(null,e,today.minusDays(1).toString(),"Service",0,100,"","",today.plusDays(30).toString(),151.0,"",""));var d=new DashboardStore(store,true);assertEquals(1,d.alerts(today).size());w.saveService(new WorkStore.Service(service,e,today.minusDays(1).toString(),"Service",0,100,"","",today.plusDays(31).toString(),151.0,"",""));assertTrue(d.alerts(today).isEmpty());w.saveService(new WorkStore.Service(service,e,today.minusDays(1).toString(),"Service",0,100,"","","",100.0,"",""));assertEquals(0,d.alerts(today).get(0).severity());var machine=w.equipment().get(0);w.saveEquipment(new WorkStore.Equipment(e,machine.name(),"","","","","","hours",100,"Πωλήθηκε","",""));assertTrue(d.alerts(today).isEmpty());String p=w.saveProtection(new WorkStore.Protection(null,today.toString(),f,"","Purpose","Product","","",1,"L",1,1,"","",3,0,"",0,"",""));assertEquals(0,d.alerts(today).get(0).severity());assertEquals(1,d.alerts(today.plusDays(1)).get(0).severity());assertTrue(d.alerts(today.plusDays(3)).isEmpty());w.deleteProtection(p);assertTrue(d.alerts(today).isEmpty());}finally{context.deleteDatabase(name);}}
    @Test public void profileIsolationAndEmptyState(){String one="dashboard-profile-one.db",two="dashboard-profile-two.db";context.deleteDatabase(one);context.deleteDatabase(two);try(var a=new FarmStore(context,one);var b=new FarmStore(context,two)){a.addField("Private",1);new InventoryStore(a).saveItem(new InventoryStore.Item(null,"Private item","","kg",0,""));var s=new DashboardStore(b,true).snapshot("",LocalDate.now());assertEquals(0,s.fields());assertEquals(0,s.income().signum());assertTrue(s.products().isEmpty());assertTrue(s.alerts().isEmpty());assertEquals(1,new DashboardStore(a,true).alerts(LocalDate.now()).size());}finally{context.deleteDatabase(one);context.deleteDatabase(two);}}
}
