package gr.mastixa.manager;
import android.app.Activity;
import android.content.Intent;
import android.view.*;
import android.widget.*;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.*;
public class DocumentsReportsUiTest {
    private List<View> views(View v){var out=new ArrayList<View>();out.add(v);if(v instanceof ViewGroup g)for(int n=0;n<g.getChildCount();n++)out.addAll(views(g.getChildAt(n)));return out;}
    private void click(String label){var roots=android.view.inspector.WindowInspector.getGlobalWindowViews();for(int n=roots.size()-1;n>=0;n--)for(var v:views(roots.get(n)))if(v instanceof Button b&&b.getText().toString().equals(label)){b.performClick();return;}fail("Missing button "+label);}
    private void fill(String label,String value){for(var root:android.view.inspector.WindowInspector.getGlobalWindowViews())for(var v:views(root))if(v instanceof EditText e&&label.contentEquals(e.getContentDescription())){e.setText(value);return;}fail("Missing input "+label);}
    private void choose(String label,int index){for(var root:android.view.inspector.WindowInspector.getGlobalWindowViews())for(var v:views(root))if(v instanceof Spinner s&&label.contentEquals(s.getContentDescription())){s.setSelection(index);return;}fail("Missing spinner "+label);}
    private void invoke(Activity activity,String name,Class<?>[] types,Object...args){try{var m=MainActivity.class.getDeclaredMethod(name,types);m.setAccessible(true);m.invoke(activity,args);}catch(Exception e){throw new RuntimeException(e);}}
    private void screenshot(String name)throws Exception{var i=InstrumentationRegistry.getInstrumentation();Thread.sleep(400);try(var out=new java.io.FileOutputStream(new java.io.File(i.getTargetContext().getExternalFilesDir(null),name))){i.getUiAutomation().takeScreenshot().compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}}
    @Test public void greekInvoiceEditOcrReviewAndSourceNavigation()throws Exception{var i=InstrumentationRegistry.getInstrumentation();var context=i.getTargetContext();var profile=new ProfileStore.Profile("documents-ui","Δοκιμή τιμολογίων","ui","el");context.deleteDatabase(profile.database());String id;try(var store=new FarmStore(context,profile.database())){id=new DocumentStore(store).add("Δοκιμαστικό τιμολόγιο.png",DocumentTest.invoice());}Activity a=null;try{i.runOnMainSync(()->{UserSession.clear();UserSession.signIn(profile);});a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));var screen=a;i.runOnMainSync(()->{click("Ενότητες");click("Έγγραφα Τιμολογίων  ›");invoke(screen,"editDocument",new Class[]{String.class,org.json.JSONObject.class},id,null);});i.waitForIdleSync();i.runOnMainSync(()->{fill("Ημερομηνία (YYYY-MM-DD)","2026-09-08");fill("Προμηθευτής / Αγοραστής","Δοκιμαστικός συνεργάτης");fill("Αριθμός τιμολογίου","000123");fill("Τελικό ποσό","123,45");fill("Κατηγορία","Εφόδια");choose("Τύπος εγγράφου",1);click("Αποθήκευση");});i.waitForIdleSync();screenshot("documents-ui.png");try(var store=new FarmStore(context,profile.database())){var docs=new DocumentStore(store);assertEquals("000123",docs.get(id).metadata().getString("invoice_number"));assertTrue(new MoneyStore(store).entries(null).isEmpty());docs.post(id);}i.runOnMainSync(()->{click("Ενότητες");click("Έξοδα  ›");click("Στοιχεία εγγραφής");});i.waitForIdleSync();i.runOnMainSync(()->click("Τιμολόγιο"));i.waitForIdleSync();i.runOnMainSync(()->click("Κλείσιμο"));i.waitForIdleSync();i.runOnMainSync(()->click("‹ Πίσω"));i.waitForIdleSync();try(var store=new FarmStore(context,profile.database())){new DocumentStore(store).unpost(id);assertTrue(new MoneyStore(store).entries(null).isEmpty());}
        }finally{var screen=a;i.runOnMainSync(()->{if(screen!=null)screen.finish();UserSession.clear();});}}
    @Test public void englishYearLockReportFiltersBackAndPdf()throws Exception{var i=InstrumentationRegistry.getInstrumentation();var context=i.getTargetContext();var profile=new ProfileStore.Profile("reports-ui","Reports test","ui","en");context.deleteDatabase(profile.database());try(var store=new FarmStore(context,profile.database());var in=i.getContext().getAssets().open("windows-production.zip")){CatalogImport.apply(store,CatalogImport.read(in),new java.io.File(context.getCacheDir(),"report-ui-import.json"));}Activity a=null;try{i.runOnMainSync(()->{UserSession.clear();UserSession.signIn(profile);});a=i.startActivitySync(new Intent(context,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK));var screen=a;i.runOnMainSync(()->{invoke(screen,"navigate",new Class[]{String.class},"Κλείδωμα Έτους");click("Manage year");});i.waitForIdleSync();i.runOnMainSync(()->{fill("Year","2026");fill("Reason","Year completed");click("Save");});i.waitForIdleSync();try(var store=new FarmStore(context,profile.database())){assertTrue(YearLocks.locked(store.getReadableDatabase(),"2026"));}screenshot("year-lock-ui.png");i.runOnMainSync(()->{invoke(screen,"navigate",new Class[]{String.class},"Ετήσια Αναφορά Εκμετάλλευσης");click("Report filters");});i.waitForIdleSync();i.runOnMainSync(()->{fill("From (YYYY-MM-DD, blank = all)","2026-01-01");fill("To (YYYY-MM-DD, blank = all)","2026-12-31");click("Save");});i.waitForIdleSync();screenshot("reports-ui.png");i.runOnMainSync(()->{click("‹ Back");invoke(screen,"navigate",new Class[]{String.class},"Αναφορά Αποθήκης & Αξίας Stock");});i.waitForIdleSync();screenshot("stock-report-ui.png");}finally{var screen=a;i.runOnMainSync(()->{if(screen!=null)screen.finish();UserSession.clear();});}}
}
