package gr.mastixa.manager;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import static org.junit.Assert.*;
import org.json.*;
import java.io.*;
import java.util.*;

public class DocumentTest {
    final android.content.Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    static byte[] invoice(){var b=android.graphics.Bitmap.createBitmap(1400,700,android.graphics.Bitmap.Config.ARGB_8888);var canvas=new android.graphics.Canvas(b);canvas.drawColor(android.graphics.Color.WHITE);var p=new android.graphics.Paint(android.graphics.Paint.ANTI_ALIAS_FLAG);p.setColor(android.graphics.Color.BLACK);p.setTextSize(48);canvas.drawText("SUPPLIER: MASTIXA TEST",60,110,p);canvas.drawText("08/09/2026",60,210,p);canvas.drawText("TOTAL 123.45",60,310,p);canvas.drawText("ΣΥΝΟΛΟ 123,45",60,410,p);var out=new ByteArrayOutputStream();b.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);b.recycle();return out.toByteArray();}
    static JSONObject metadata(DocumentStore.Document d)throws Exception{return new JSONObject(d.metadata().toString()).put("supplier","Test Supplier").put("invoice_number","000012").put("amount_text","123,45").put("document_type","purchase").put("category","Supplies").put("notes","First;\nSecond");}
    @Test public void attachmentFinanceDuplicateProtectionBackupAndLocks()throws Exception{String name="documents-local.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"documents-local.json");try(var store=new FarmStore(context,name)){var docs=new DocumentStore(store);String id=docs.add("invoice.png",invoice());docs.save(id,"2026-09-08",metadata(docs.get(id)));assertTrue(new MoneyStore(store).entries(null).isEmpty());String money=docs.post(id);assertEquals(123.45,new MoneyStore(store).entries("expense").get(0).amount(),0);try{docs.post(id);fail();}catch(IllegalArgumentException expected){}assertEquals(1,new MoneyStore(store).entries(null).size());try{docs.delete(id);fail();}catch(IllegalArgumentException expected){}try{new MoneyStore(store).delete(money);fail();}catch(IllegalArgumentException expected){}YearLocks.set(store.getWritableDatabase(),"2026",true,"Closed");byte[] backup=LocalBackup.snapshot(store);LocalBackup.restore(store,backup,file);assertArrayEquals(invoice(),android.util.Base64.decode(docs.get(id).attachment(),android.util.Base64.DEFAULT));assertEquals(money,docs.get(id).financialId());assertTrue(YearLocks.locked(store.getReadableDatabase(),"2026"));}finally{context.deleteDatabase(name);file.delete();}}
    @Test public void realOfflineGreekEnglishImageAndPdfOcr()throws Exception{String text=OfflineOcr.recognize(context,invoice(),"invoice.png");assertTrue(text,text.contains("123"));assertTrue(text,text.toUpperCase(Locale.ROOT).contains("ΣΥΝΟΛΟ"));var hints=OfflineOcr.suggestions(text);assertEquals("2026-09-08",hints.getString("ocr_suggested_date"));assertEquals("123.45",hints.getString("ocr_suggested_amount"));var pdf=ReportStore.pdf(List.<String[]>of(new String[]{"SUPPLIER","MASTIXA TEST"},new String[]{"DATE","08/09/2026"},new String[]{"TOTAL","123.45"}));String pdfText=OfflineOcr.recognize(context,pdf,"invoice.pdf");assertTrue(pdfText,pdfText.contains("123.45"));}
    @Test public void hintsRejectImpossibleDatesAndUnlabelledPrices()throws Exception{var hints=OfflineOcr.suggestions("31/02/2026\nprice 12.00\nSUPPLIER: Example LTD\nTOTAL 1.234,56");assertFalse(hints.has("ocr_suggested_date"));assertEquals("1234.56",hints.getString("ocr_suggested_amount"));assertEquals("Example LTD",hints.getString("ocr_suggested_supplier"));assertFalse(OfflineOcr.suggestions("price 99.95").has("ocr_suggested_amount"));}
    @Test public void realWindowsDocumentsAttachmentsRelationsLocksAndRepeat()throws Exception{String name="documents-windows.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"documents-import.json");try(var store=new FarmStore(context,name);var in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("windows-documents.zip")){var data=CatalogImport.read(in);assertEquals(1,CatalogImport.preview(store,data).documents());assertEquals(1,CatalogImport.preview(store,data).yearLocks());CatalogImport.apply(store,data,file);var docs=new DocumentStore(store);var d=docs.list().get(0);assertEquals("000012",d.metadata().getString("invoice_number"));assertEquals("10,25",d.metadata().getString("amount_text"));assertFalse(d.attachment().isEmpty());assertFalse(d.financialId().isEmpty());assertFalse(d.metadata().getString("partner_id").isEmpty());assertEquals(2,new MoneyStore(store).entries("expense").size());assertTrue(YearLocks.locked(store.getReadableDatabase(),"2026"));var again=CatalogImport.apply(store,data,file);assertEquals(0,again.documents());assertEquals(0,again.yearLocks());assertEquals(1,docs.list().size());LocalBackup.inspect(store,LocalBackup.snapshot(store));}finally{context.deleteDatabase(name);file.delete();}}
    @Test public void corruptedAttachmentAndMissingFinancialLinkRollback()throws Exception{String name="documents-invalid.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){var docs=new DocumentStore(store);String id=docs.add("invoice.png",invoice());var e=new JSONObject(new String(LocalBackup.snapshot(store),java.nio.charset.StandardCharsets.UTF_8));var payload=new JSONObject(e.getString("payload"));payload.getJSONArray("invoice_documents").getJSONObject(0).put("sha256","wrong");String data=payload.toString();byte[] bad=e.put("payload",data).put("sha256",DocumentStore.hash(data.getBytes(java.nio.charset.StandardCharsets.UTF_8))).toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);try{LocalBackup.inspect(store,bad);fail();}catch(IllegalArgumentException expected){}assertEquals(1,docs.list().size());try{docs.add("../outside.png",invoice());fail();}catch(IllegalArgumentException expected){}assertEquals(1,docs.list().size());}finally{context.deleteDatabase(name);}}
    @Test public void unpostedDeleteAndArchiveKeepOriginalBytes()throws Exception{String name="documents-archive.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){var docs=new DocumentStore(store);String id=docs.add("invoice.png",invoice());byte[] archive=DocumentPackage.export(docs.list());boolean attachment=false,manifest=false;try(var zip=new java.util.zip.ZipInputStream(new ByteArrayInputStream(archive))){java.util.zip.ZipEntry e;while((e=zip.getNextEntry())!=null){var out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=zip.read(b))!=-1)out.write(b,0,n);if(e.getName().startsWith("invoices/")){attachment=true;assertArrayEquals(invoice(),out.toByteArray());}else if(e.getName().equals("manifest.json")){manifest=true;assertEquals(1,new JSONObject(out.toString("UTF-8")).getInt("count"));}}}assertTrue(attachment&&manifest);docs.delete(id);assertTrue(docs.list().isEmpty());LocalBackup.inspect(store,LocalBackup.snapshot(store));}finally{context.deleteDatabase(name);}}

    @Test public void legacyInvoicePackageAttachesOnceWithoutCreatingFinance()throws Exception{String name="documents-legacy-files.db";context.deleteDatabase(name);var recovery=new File(context.getCacheDir(),"documents-legacy-files.json");try(var store=new FarmStore(context,name)){var docs=new DocumentStore(store);String id=docs.add("invoice.png",invoice());docs.save(id,"2026-09-08",metadata(docs.get(id)));byte[] archive=DocumentPackage.export(docs.list());var d=docs.get(id);docs.put(new DocumentStore.Document(id,d.date(),d.metadata(),"","","",d.windowsId()));var plan=DocumentPackage.preview(store,new ByteArrayInputStream(archive));assertEquals(1,plan.size());YearLocks.set(store.getWritableDatabase(),"2026",true,"Closed");try{DocumentPackage.apply(store,plan,recovery);fail();}catch(android.database.sqlite.SQLiteConstraintException expected){}assertTrue(docs.get(id).attachment().isEmpty());YearLocks.set(store.getWritableDatabase(),"2026",false,"Attach historical file");DocumentPackage.apply(store,plan,recovery);assertArrayEquals(invoice(),android.util.Base64.decode(docs.get(id).attachment(),android.util.Base64.DEFAULT));assertTrue(DocumentPackage.preview(store,new ByteArrayInputStream(archive)).isEmpty());assertTrue(new MoneyStore(store).entries(null).isEmpty());}finally{context.deleteDatabase(name);recovery.delete();}}
    @Test public void schema11MigrationAndReverseRepostPreserveRecovery()throws Exception{String name="documents-stage11.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"documents-stage11.json");byte[] old;try{try(var store=new FarmStore(context,name)){store.addField("Existing field",2);var envelope=new JSONObject(new String(LocalBackup.snapshot(store),java.nio.charset.StandardCharsets.UTF_8));var payload=new JSONObject(envelope.getString("payload"));payload.remove("invoice_documents");payload.remove("year_locks");payload.remove("gis_records");LegacySchema.removeSync(payload);String data=payload.toString();old=envelope.put("schema",11).put("payload",data).put("sha256",DocumentStore.hash(data.getBytes(java.nio.charset.StandardCharsets.UTF_8))).toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);LegacySchema.dropStage12(store.getWritableDatabase());store.getWritableDatabase().setVersion(11);}try(var store=new FarmStore(context,name)){assertEquals(14,store.getReadableDatabase().getVersion());var docs=new DocumentStore(store);String id=docs.add("invoice.png",invoice());docs.save(id,"2026-09-08",metadata(docs.get(id)));docs.post(id);YearLocks.set(store.getWritableDatabase(),"2026",true,"Closed");try{docs.unpost(id);fail();}catch(android.database.sqlite.SQLiteConstraintException expected){}assertEquals(1,new MoneyStore(store).entries(null).size());YearLocks.set(store.getWritableDatabase(),"2026",false,"Correction");docs.unpost(id);assertTrue(new MoneyStore(store).entries(null).isEmpty());docs.save(id,"2026-09-08",metadata(docs.get(id)).put("amount_text","150"));docs.post(id);assertEquals(150,new MoneyStore(store).entries(null).get(0).amount(),0);LocalBackup.inspect(store,LocalBackup.snapshot(store));LocalBackup.restore(store,old,file);assertTrue(docs.list().isEmpty());assertTrue(new MoneyStore(store).entries(null).isEmpty());assertEquals(1,store.fields().size());LocalBackup.inspect(store,java.nio.file.Files.readAllBytes(file.toPath()));}}finally{context.deleteDatabase(name);file.delete();}}
}
