package gr.mastixa.manager;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;
import java.util.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import org.json.*;

public class EquipmentTest {
    private final android.content.Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    private CatalogImport.Package fixture() throws Exception{try(var in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("windows-equipment.zip")){return CatalogImport.read(in);}}
    private WorkStore.Equipment machine(){return new WorkStore.Equipment(null,"Tractor","Tractor","Model","001","","Diesel","hours",100,"Ενεργό","Notes","");}
    private WorkStore.Service service(String id,String equipment,double cost,double meter,String next,Double nextMeter){return new WorkStore.Service(id,equipment,"2026-09-08","Service",cost,meter,"Technician","Notes",next,nextMeter,"","");}
    @Test public void serviceExpenseMeterLifecycleAndRollback() throws Exception {
        String name="equipment-local-test.db";context.deleteDatabase(name);
        try(var store=new FarmStore(context,name)){var w=new WorkStore(store);String equipment=w.saveEquipment(machine());String id=w.saveService(service(null,equipment,50,120,"",null));var expense=new MoneyStore(store).entries("expense").get(0);assertEquals(120,w.equipment().get(0).current_meter(),0);assertEquals(50,expense.amount(),0);assertEquals(id,expense.sourceId());
            w.saveService(service(id,equipment,60,110,"",null));assertEquals(120,w.equipment().get(0).current_meter(),0);assertEquals(expense.id(),new MoneyStore(store).entries("expense").get(0).id());assertEquals(60,new MoneyStore(store).entries("expense").get(0).amount(),0);
            byte[] before=LocalBackup.snapshot(store);store.getWritableDatabase().execSQL("CREATE TRIGGER reject_service_expense BEFORE UPDATE ON money_entries BEGIN SELECT RAISE(ABORT,'test'); END");try{w.saveService(service(id,equipment,70,150,"",null));fail();}catch(android.database.SQLException expected){}assertArrayEquals(before,LocalBackup.snapshot(store));try{w.deleteService(id);fail();}catch(android.database.SQLException expected){}assertArrayEquals(before,LocalBackup.snapshot(store));store.getWritableDatabase().execSQL("DROP TRIGGER reject_service_expense");
            try{w.deleteEquipment(equipment);fail();}catch(IllegalArgumentException expected){}w.saveService(service(id,equipment,0,120,"",null));assertTrue(new MoneyStore(store).entries(null).isEmpty());w.saveService(service(id,equipment,80,120,"",null));assertEquals(expense.id(),new MoneyStore(store).entries("expense").get(0).id());w.deleteService(id);assertTrue(new MoneyStore(store).entries(null).isEmpty());assertEquals(120,w.equipment().get(0).current_meter(),0);w.deleteEquipment(equipment);LocalBackup.inspect(store,LocalBackup.snapshot(store));
        }finally{context.deleteDatabase(name);}
    }
    @Test public void remindersAndMeterUnitHistory() throws Exception{
        String name="equipment-reminders-test.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){var w=new WorkStore(store);String equipment=w.saveEquipment(machine());var today=java.time.LocalDate.of(2026,9,8);assertEquals("none",w.reminder(w.equipment().get(0),today));String id=w.saveService(service(null,equipment,0,100,"2026-10-08",null));assertEquals("upcoming",w.reminder(w.equipment().get(0),today));w.saveService(service(id,equipment,0,100,"2026-09-07",null));assertEquals("overdue",w.reminder(w.equipment().get(0),today));w.saveService(service(id,equipment,0,100,"",200.0));assertEquals("planned",w.reminder(w.equipment().get(0),today));w.saveService(service(id,equipment,0,100,"",150.0));assertEquals("upcoming",w.reminder(w.equipment().get(0),today));w.saveService(service(id,equipment,0,100,"",100.0));assertEquals("overdue",w.reminder(w.equipment().get(0),today));var e=w.equipment().get(0);try{w.saveEquipment(new WorkStore.Equipment(e.id(),e.name(),e.category(),e.brand_model(),e.equipment_code(),e.purchase_date(),e.fuel(),"km",e.current_meter(),e.status(),e.notes(),""));fail();}catch(IllegalArgumentException expected){}}
        finally{context.deleteDatabase(name);}
    }
    @Test public void realWindowsZipAllFieldsExpenseRepeatAndBackup() throws Exception {
        String name="equipment-import-test.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"equipment-import.json");try(var store=new FarmStore(context,name)){var d=fixture();var plan=CatalogImport.preview(store,d);assertEquals(1,plan.equipment());assertEquals(2,plan.services());assertTrue(store.fields().isEmpty());CatalogImport.apply(store,d,file);var w=new WorkStore(store);var e=w.equipment().get(0);var a=w.services().stream().filter(s->s.cost()>0).findFirst().orElseThrow();assertEquals("00012",e.equipment_code());assertEquals("2020-01-15",e.purchase_date());assertEquals("Μοντέλο Α",e.brand_model());assertEquals("Diesel",e.fuel());assertEquals("hours",e.meter_type());assertEquals(120,e.current_meter(),0);assertEquals("Μηχάνημα;\nδεύτερη γραμμή",e.notes());assertEquals(e.id(),a.equipment_id());assertEquals("2027-06-01",a.next_service_date());assertEquals(220,a.next_service_meter(),0);assertEquals("Δοκιμαστικός τεχνικός",a.technician());assertEquals("Service;\nδεύτερη γραμμή",a.notes());var expense=new MoneyStore(store).entries("expense").stream().filter(x->x.sourceType().equals("equipment_maintenance")).findFirst().orElseThrow();assertEquals(a.id(),expense.sourceId());assertEquals(85.5,expense.amount(),0);assertEquals(3,new MoneyStore(store).entries("expense").size());assertEquals(18,CatalogImport.apply(store,d,file).skipped());byte[] backup=LocalBackup.snapshot(store);LocalBackup.restore(store,backup,file);assertNull(w.services().stream().filter(x->x.cost()==0).findFirst().orElseThrow().next_service_meter());try{w.deleteService(a.id());fail();}catch(IllegalArgumentException expected){}}
        finally{context.deleteDatabase(name);file.delete();}
    }
    private CatalogImport.Package withEquipment(CatalogImport.Package d,EquipmentImport.Data equipment){return new CatalogImport.Package(d.fields(),d.producer(),d.products(),d.links(),d.partners(),d.inventory(),d.money(),d.production(),d.activities(),new WorkImport.Data(d.work().protections(),d.work().workers(),d.work().labor(),d.work().plantings(),equipment),d.ignored());}
    @Test public void identicalNamesRemainDistinctAndAmbiguousLocalMatchRejected() throws Exception {
        var d=fixture();var a=d.work().equipment().equipment().get(0);var other=new WorkStore.Equipment(null,a.name(),a.category(),a.brand_model(),a.equipment_code(),a.purchase_date(),a.fuel(),a.meter_type(),a.current_meter(),a.status(),a.notes(),"other");var data=withEquipment(d,new EquipmentImport.Data(List.of(a,other),List.of()));String name="equipment-names-test.db";context.deleteDatabase(name);
        try(var store=new FarmStore(context,name)){assertEquals(2,EquipmentImport.process(store,data,false).equipment());assertEquals(2,EquipmentImport.process(store,data,true).equipment());assertEquals(2,new WorkStore(store).equipment().size());assertEquals(2,EquipmentImport.process(store,data,true).skipped());}finally{context.deleteDatabase(name);}
        try(var store=new FarmStore(context,name)){new WorkStore(store).saveEquipment(new WorkStore.Equipment(null,a.name(),a.category(),a.brand_model(),a.equipment_code(),a.purchase_date(),a.fuel(),a.meter_type(),a.current_meter(),a.status(),a.notes(),""));try{EquipmentImport.process(store,data,false);fail();}catch(IllegalArgumentException expected){}}finally{context.deleteDatabase(name);}
    }
    @Test public void existingExpenseLinkedWithoutDuplicate() throws Exception{
        String name="equipment-prior-test.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"equipment-prior.json");try(var store=new FarmStore(context,name)){var d=fixture();CatalogImport.apply(store,withEquipment(d,EquipmentImport.Data.empty()),file);var before=new MoneyStore(store).entries("expense").stream().filter(e->e.sourceType().equals("windows:equipment_maintenance")).findFirst().orElseThrow();CatalogImport.apply(store,d,file);var after=new MoneyStore(store).entries("expense").stream().filter(e->e.sourceType().equals("equipment_maintenance")).findFirst().orElseThrow();assertEquals(before.id(),after.id());assertEquals(3,new MoneyStore(store).entries("expense").size());}finally{context.deleteDatabase(name);file.delete();}
    }
    @Test public void missingExpenseRejectedAndImportFailureRollsBack() throws Exception{
        String name="equipment-invalid-test.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"equipment-invalid.json");try(var store=new FarmStore(context,name)){var d=fixture();var money=d.money().stream().filter(e->!e.sourceType().equals("equipment_maintenance")).toList();var bad=new CatalogImport.Package(d.fields(),d.producer(),d.products(),d.links(),d.partners(),d.inventory(),money,d.production(),d.activities(),d.work(),d.ignored());try{CatalogImport.preview(store,bad);fail();}catch(IllegalArgumentException expected){}byte[] before=LocalBackup.snapshot(store);store.getWritableDatabase().execSQL("CREATE TRIGGER reject_service_import BEFORE INSERT ON equipment_maintenance BEGIN SELECT RAISE(ABORT,'test'); END");try{CatalogImport.apply(store,d,file);fail();}catch(android.database.SQLException expected){}assertArrayEquals(before,LocalBackup.snapshot(store));}finally{context.deleteDatabase(name);file.delete();}
    }
    private byte[] envelope(JSONObject e,JSONObject p,int schema) throws Exception{String data=p.toString();var h=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(data.getBytes(StandardCharsets.UTF_8)))h.append(String.format("%02x",b&255));return e.put("schema",schema).put("payload",data).put("sha256",h.toString()).toString().getBytes(StandardCharsets.UTF_8);}
    @Test public void schemaTenUpgradeRestoreAndBadExpenseRejected() throws Exception{
        String name="equipment-upgrade-test.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"equipment-old.json");byte[] old;try{try(var store=new FarmStore(context,name)){store.addField("Field",1);var e=new JSONObject(new String(LocalBackup.snapshot(store),StandardCharsets.UTF_8));var p=new JSONObject(e.getString("payload"));p.remove("equipment");p.remove("equipment_maintenance");p.remove("invoice_documents");p.remove("year_locks");p.remove("gis_records");LegacySchema.removeSync(p);old=envelope(e,p,10);var db=store.getWritableDatabase();LegacySchema.dropStage12(db);db.execSQL("DROP TABLE equipment_maintenance");db.execSQL("DROP TABLE equipment");db.execSQL("DROP INDEX money_service");db.setVersion(10);}try(var store=new FarmStore(context,name)){assertEquals(14,store.getReadableDatabase().getVersion());var w=new WorkStore(store);String id=w.saveEquipment(machine());w.saveService(service(null,id,50,120,"",null));var e=new JSONObject(new String(LocalBackup.snapshot(store),StandardCharsets.UTF_8));var p=new JSONObject(e.getString("payload"));p.getJSONArray("equipment_maintenance").getJSONObject(0).put("cost",51);try{LocalBackup.inspect(store,envelope(e,p,14));fail();}catch(IOException expected){}LocalBackup.restore(store,old,file);assertTrue(w.equipment().isEmpty());assertTrue(w.services().isEmpty());assertTrue(new MoneyStore(store).entries(null).isEmpty());assertEquals(1,store.fields().size());}}finally{context.deleteDatabase(name);file.delete();}
    }
}
