package gr.mastixa.manager;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;
import java.util.*;
public class ReportsLocksTest {
    final android.content.Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    private void locked(Runnable run){try{run.run();fail("Expected year guard");}catch(android.database.sqlite.SQLiteConstraintException e){assertTrue(e.getMessage(),e.getMessage().contains("Year is locked"));}}
    private MoneyStore.Entry entry(String id,String date,double amount){return new MoneyStore.Entry(id,"expense",date,"","Supplies","Test","","","",amount,"","","","");}
    @Test public void databaseGuardsEveryAnnualTableAndBothOldAndNewDates()throws Exception{String name="year-guards.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){var db=store.getWritableDatabase();var money=new MoneyStore(store);String old=money.save(entry(null,"2026-01-01",10)),open=money.save(entry(null,"2027-01-01",20));YearLocks.set(db,"2026",true,"Final");for(var pair:YearLocks.DATED)locked(()->db.execSQL("INSERT INTO "+pair[0]+"("+pair[1]+") VALUES('2026-02-01')"));locked(()->money.save(entry(old,"2027-02-01",12)));locked(()->money.save(entry(open,"2026-02-01",12)));locked(()->money.delete(old));locked(()->db.delete("money_entries","id=?",new String[]{old}));assertEquals(30,MoneyStore.total(money.entries(null)).doubleValue(),0);store.addField("Master still editable",1);YearLocks.set(db,"2026",false,"Correction");money.delete(old);assertEquals(1,money.entries(null).size());LocalBackup.inspect(store,LocalBackup.snapshot(store));}finally{context.deleteDatabase(name);}}
    @Test public void linkedServiceRollbackPreservesExpenseMachineAndQueue()throws Exception{String name="year-service.db";context.deleteDatabase(name);try(var store=new FarmStore(context,name)){var w=new WorkStore(store);String machine=w.saveEquipment(new WorkStore.Equipment(null,"Tractor","","","","","","hours",10,"Ενεργό","",""));String id=w.saveService(new WorkStore.Service(null,machine,"2026-01-01","Oil",25,15,"","","",null,"",""));YearLocks.set(store.getWritableDatabase(),"2026",true,"Closed");int queue;try(var c=store.getReadableDatabase().rawQuery("SELECT count(*) FROM pending_changes",null)){c.moveToFirst();queue=c.getInt(0);}locked(()->w.saveService(new WorkStore.Service(id,machine,"2027-01-01","Oil",50,99,"","","",null,"","")));assertEquals(15,w.equipment().get(0).current_meter(),0);assertEquals(25,new MoneyStore(store).entries("expense").get(0).amount(),0);try(var c=store.getReadableDatabase().rawQuery("SELECT count(*) FROM pending_changes",null)){c.moveToFirst();assertEquals(queue,c.getInt(0));}}finally{context.deleteDatabase(name);}}
    @Test public void lockedImportRollsBackNewMasterRecordsToo()throws Exception{String name="year-import.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"locked-import.json");try(var store=new FarmStore(context,name);var in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("windows-documents.zip")){YearLocks.set(store.getWritableDatabase(),"2026",true,"Closed");var data=CatalogImport.read(in);try{CatalogImport.apply(store,data,file);fail();}catch(android.database.sqlite.SQLiteConstraintException expected){}assertTrue(store.fields().isEmpty());assertTrue(new CatalogStore(store).products().isEmpty());assertTrue(new DocumentStore(store).list().isEmpty());assertTrue(YearLocks.locked(store.getReadableDatabase(),"2026"));}finally{context.deleteDatabase(name);file.delete();}}
    @Test public void reportTotalsFiltersStockAndNoDuplicateSourceMoney()throws Exception{String name="reports-totals.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"reports-import.json");try(var store=new FarmStore(context,name);var in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("windows-production.zip")){CatalogImport.apply(store,CatalogImport.read(in),file);var r=new ReportStore(store,true);var all=new ReportStore.Filter("2026-01-01","2026-12-31","","","");var rows=r.report("Αναφορές",all);assertEquals("171.50 €",rows.stream().filter(x->x[0].equals("Posted income")).findFirst().orElseThrow()[1]);assertEquals("60.25 €",rows.stream().filter(x->x[0].equals("Posted expenses")).findFirst().orElseThrow()[1]);assertEquals("111.25 €",rows.stream().filter(x->x[0].equals("Financial result")).findFirst().orElseThrow()[1]);var s=r.stock().get(0);assertEquals(17,s.quantity(),0);assertEquals(2.5,s.average(),0);assertEquals(42.5,s.value(),0);assertEquals(14,new ProductionStore(store).available(new CatalogStore(store).products().get(0).id()),0);var none=r.report("Αναφορές",new ReportStore.Filter("2025-01-01","2025-12-31","","",""));assertEquals("0.00 €",none.stream().filter(x->x[0].equals("Posted income")).findFirst().orElseThrow()[1]);for(String page:ReportStore.PAGES){assertFalse(r.report(page,all).isEmpty());assertTrue(ReportStore.pdf(r.report(page,all)).length>100);}try{new ReportStore.Filter("2026-12-31","2026-01-01","","","");fail();}catch(IllegalArgumentException expected){}}finally{context.deleteDatabase(name);file.delete();}}
    @Test public void csvEscapesFormulasAndMultilinePdfPaginates()throws Exception{var rows=new ArrayList<String[]>();rows.add(new String[]{"=HYPERLINK(\"url\")","Line one;\nLine two"});for(int n=0;n<140;n++)rows.add(new String[]{"Ελληνική αναφορά "+n,"Πληροφορίες δοκιμής"});String csv=new String(ReportStore.csv(rows),java.nio.charset.StandardCharsets.UTF_8);assertTrue(csv,csv.startsWith("\uFEFF\"'=HYPERLINK("));assertTrue(csv.contains("Line one;\nLine two"));byte[] pdf=ReportStore.pdf(rows);File f=new File(context.getCacheDir(),"report-pages.pdf");try{try(var out=new FileOutputStream(f)){out.write(pdf);}try(var fd=android.os.ParcelFileDescriptor.open(f,android.os.ParcelFileDescriptor.MODE_READ_ONLY);var renderer=new android.graphics.pdf.PdfRenderer(fd)){assertTrue(renderer.getPageCount()>1);}}finally{f.delete();}}

    @Test public void annualHistoricalStockBuyerSummaryAndExcelExport()throws Exception{String name="reports-history.db";context.deleteDatabase(name);var file=new File(context.getCacheDir(),"reports-history.json");try(var store=new FarmStore(context,name);var in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("windows-production.zip")){CatalogImport.apply(store,CatalogImport.read(in),file);var p=new CatalogStore(store).products().get(0);var production=new ProductionStore(store);production.saveHarvest(new ProductionStore.Harvest(null,"2027-01-01",p.id(),p.name(),store.fields().get(0).id(),5,"Later",""));var rows=new ReportStore(store,true).report("Ετήσια Αναφορά Εκμετάλλευσης",new ReportStore.Filter("2026-01-01","2026-12-31","","",""));assertTrue(rows.stream().anyMatch(x->x[0].contains("Stock through 2026-12-31")&&x[1].startsWith("14.00 kg")));assertTrue(rows.stream().anyMatch(x->x[0].contains("Sales count / Average price")&&x[1].startsWith("1 / 8.50")));assertTrue(rows.stream().anyMatch(x->x[1].contains("1 sales · 6.00 kg · 51.00 €")));byte[] xlsx=ReportStore.xlsx(rows);try(var zip=new java.util.zip.ZipInputStream(new ByteArrayInputStream(xlsx))){int files=0;java.util.zip.ZipEntry e;while((e=zip.getNextEntry())!=null){files++;var bytes=new ByteArrayOutputStream();byte[] b=new byte[8192];int count;while((count=zip.read(b))!=-1)bytes.write(b,0,count);javax.xml.parsers.DocumentBuilderFactory.newInstance().newDocumentBuilder().parse(new ByteArrayInputStream(bytes.toByteArray()));}assertEquals(5,files);}try(var out=new FileOutputStream(new File(context.getExternalFilesDir(null),"verified-report.xlsx"))){out.write(xlsx);}try(var out=new FileOutputStream(new File(context.getExternalFilesDir(null),"verified-report.pdf"))){out.write(ReportStore.pdf(rows));}}finally{context.deleteDatabase(name);file.delete();}}
}
