from .icon_normalization import install_icon_normalization
from .icon_normalization_performance import install_icon_normalization_performance
from .focus_accessibility import install_focus_accessibility
from .help_accessibility import install_help_accessibility

install_icon_normalization()
install_icon_normalization_performance()
install_focus_accessibility()
install_help_accessibility()
