package gr.mastixa.manager;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import android.util.Base64;
import org.json.*;
import java.util.*;
import java.io.*;

/** Attachments live inside the profile database so backups and transactions include their bytes. */
public final class DocumentStore {
    static final String[] COLUMNS={"id","invoice_date","metadata","attachment","sha256","financial_id","windows_id","revision","updated_at","deleted_at"};
    public record Document(String id,String date,JSONObject metadata,String attachment,String sha,String financialId,String windowsId){}
    private final FarmStore store;
    public DocumentStore(FarmStore store){this.store=store;}
    static void create(SQLiteDatabase db){db.execSQL("CREATE TABLE IF NOT EXISTS invoice_documents(id TEXT PRIMARY KEY,invoice_date TEXT NOT NULL,metadata TEXT NOT NULL,attachment TEXT NOT NULL,sha256 TEXT NOT NULL,financial_id TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS documents_windows ON invoice_documents(windows_id) WHERE windows_id<>''");}
    public static String hash(byte[] bytes){try{var out=new StringBuilder();for(byte b:java.security.MessageDigest.getInstance("SHA-256").digest(bytes))out.append(String.format(java.util.Locale.ROOT,"%02x",b&255));return out.toString();}catch(Exception e){throw new IllegalStateException(e);}}
    public static byte[] read(InputStream in)throws IOException{if(in==null)throw new IOException("Δεν ανοίγει το αρχείο");var out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>5*1024*1024)throw new IOException("Όριο συνημμένου 5 MB / Attachment limit 5 MB");out.write(b,0,n);}if(out.size()==0)throw new IOException("Κενό αρχείο / Empty file");return out.toByteArray();}
    public static String mime(String name){String n=name.toLowerCase(Locale.ROOT);if(n.endsWith(".pdf"))return "application/pdf";if(n.endsWith(".png"))return "image/png";if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return "image/jpeg";if(n.endsWith(".webp"))return "image/webp";if(n.endsWith(".bmp"))return "image/bmp";if(n.endsWith(".tif")||n.endsWith(".tiff"))return "image/tiff";throw new IllegalArgumentException("Υποστηρίζονται PDF και εικόνες / PDF and image files only");}
    static void queue(SQLiteDatabase db,String table,String id,String op,int revision){var q=new ContentValues();q.put("operation_id",UUID.randomUUID().toString());q.put("entity",table);q.put("entity_id",id);q.put("operation",op);q.put("revision",revision);q.put("created_at",System.currentTimeMillis());db.insertOrThrow("pending_changes",null,q);}
    public List<Document> list(){var rows=new ArrayList<Document>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,invoice_date,metadata,attachment,sha256,financial_id,windows_id FROM invoice_documents WHERE deleted_at IS NULL ORDER BY invoice_date DESC,updated_at DESC",null)){while(c.moveToNext())try{rows.add(new Document(c.getString(0),c.getString(1),new JSONObject(c.getString(2)),c.getString(3),c.getString(4),c.getString(5),c.getString(6)));}catch(JSONException e){throw new IllegalStateException(e);}}return rows;}
    public Document get(String id){return list().stream().filter(x->x.id().equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException("Λείπει έγγραφο / Document missing"));}
    public static void validate(Document d){
        if(d.id()==null||d.id().isBlank())throw new IllegalArgumentException("Λείπει ταυτότητα εγγράφου");CatalogStore.validateCultivation(d.date(),"active");
        String name=d.metadata().optString("original_filename");if(name.isBlank()||name.contains("/")||name.contains("\\"))throw new IllegalArgumentException("Μη έγκυρο όνομα αρχείου");mime(name);
        if(!Set.of("unknown","purchase","sale").contains(d.metadata().optString("document_type","unknown")))throw new IllegalArgumentException("Μη έγκυρος τύπος εγγράφου");
        if(!d.attachment().isEmpty()){byte[] b=Base64.decode(d.attachment(),Base64.DEFAULT);if(b.length==0||b.length>5*1024*1024||!hash(b).equals(d.sha()))throw new IllegalArgumentException("Αλλοιωμένο συνημμένο / Damaged attachment");}else if(!d.sha().isEmpty())throw new IllegalArgumentException("Λείπει συνημμένο");
    }
    String put(Document d){validate(d);var db=store.getWritableDatabase();int rev=0;try(var c=db.rawQuery("SELECT revision FROM invoice_documents WHERE id=?",new String[]{d.id()})){if(c.moveToFirst())rev=c.getInt(0);}var v=new ContentValues();v.put("id",d.id());v.put("invoice_date",d.date());v.put("metadata",d.metadata().toString());v.put("attachment",d.attachment());v.put("sha256",d.sha());v.put("financial_id",d.financialId());v.put("windows_id",d.windowsId());v.put("revision",rev+1);v.put("updated_at",System.currentTimeMillis());v.putNull("deleted_at");if(rev==0)db.insertOrThrow("invoice_documents",null,v);else db.update("invoice_documents",v,"id=?",new String[]{d.id()});queue(db,"invoice_documents",d.id(),rev==0?"create":"update",rev+1);return d.id();}
    public String add(String name,byte[] bytes)throws JSONException{mime(name);var m=new JSONObject().put("original_filename",name).put("document_type","unknown").put("ocr_status","pending");var db=store.getWritableDatabase();db.beginTransaction();try{String id=put(new Document(UUID.randomUUID().toString(),"",m,Base64.encodeToString(bytes,Base64.NO_WRAP),hash(bytes),"",""));db.setTransactionSuccessful();return id;}finally{db.endTransaction();}}
    public void save(String id,String date,JSONObject metadata){var db=store.getWritableDatabase();db.beginTransaction();try{var old=get(id);if(!old.financialId().isEmpty())throw new IllegalArgumentException("Το έγγραφο έχει συνδεδεμένη οικονομική εγγραφή / Financial entry already linked");put(new Document(id,date,metadata,old.attachment(),old.sha(),old.financialId(),old.windowsId()));db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public void attach(String id,byte[] bytes){var db=store.getWritableDatabase();db.beginTransaction();try{var old=get(id);if(!old.attachment().isEmpty())throw new IllegalArgumentException("Υπάρχει ήδη συνημμένο");put(new Document(id,old.date(),old.metadata(),Base64.encodeToString(bytes,Base64.NO_WRAP),hash(bytes),old.financialId(),old.windowsId()));db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public String post(String id){var db=store.getWritableDatabase();db.beginTransaction();try{var d=get(id);if(!d.financialId().isEmpty()||!d.metadata().optString("financial_entry_id").isEmpty())throw new IllegalArgumentException("Έχει ήδη καταχωρηθεί / Already posted");String type=d.metadata().optString("document_type");if(!Set.of("purchase","sale").contains(type)||d.date().isEmpty())throw new IllegalArgumentException("Έλεγξε τύπο και ημερομηνία / Review type and date");double amount=amount(d.metadata().optString("amount_text"));if(amount<=0)throw new IllegalArgumentException("Χρειάζεται θετικό ποσό / Positive amount required");String category=d.metadata().optString("category","Τιμολόγιο");if(category.isBlank())category="Τιμολόγιο";
        String money=MoneyStore.put(db,new MoneyStore.Entry(null,type.equals("purchase")?"expense":"income",d.date(),"",category,"Τιμολόγιο "+d.metadata().optString("invoice_number",d.metadata().optString("original_filename")),d.metadata().optString("partner_id"),d.metadata().optString("supplier"),"",amount,d.metadata().optString("notes"),"invoice_document",id,""));put(new Document(id,d.date(),d.metadata(),d.attachment(),d.sha(),money,d.windowsId()));db.setTransactionSuccessful();return money;
    }finally{db.endTransaction();}}
    public void unpost(String id){var db=store.getWritableDatabase();db.beginTransaction();try{var d=get(id);if(!d.windowsId().isEmpty()||d.financialId().isEmpty())throw new IllegalArgumentException("Μόνο τοπική καταχώρηση μπορεί να αναιρεθεί / Only a local posting can be reversed");var e=new MoneyStore(store).entries(null).stream().filter(x->x.id().equals(d.financialId())).findFirst().orElseThrow();if(!e.sourceType().equals("invoice_document")||!e.sourceId().equals(id))throw new IllegalArgumentException("Ασυνεπής σύνδεση / Inconsistent link");MoneyStore.remove(db,e.id());put(new Document(id,d.date(),d.metadata(),d.attachment(),d.sha(),"",d.windowsId()));db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public static double amount(String value){String s=value.trim().replace(" ","");if(s.contains(","))s=s.replace(".","").replace(',','.');try{double d=Double.parseDouble(s);if(!Double.isFinite(d)||d<0||d>999999999)throw new NumberFormatException();return d;}catch(Exception e){throw new IllegalArgumentException("Μη έγκυρο ποσό / Invalid amount");}}
    public void delete(String id){var db=store.getWritableDatabase();db.beginTransaction();try{var d=get(id);if(!d.financialId().isEmpty()||!d.metadata().optString("financial_entry_id").isEmpty())throw new IllegalArgumentException("Το έγγραφο συνδέεται με οικονομικά / Document linked to finances");int rev;try(var c=db.rawQuery("SELECT revision FROM invoice_documents WHERE id=?",new String[]{id})){c.moveToFirst();rev=c.getInt(0)+1;}var v=new ContentValues();v.put("deleted_at",System.currentTimeMillis());v.put("updated_at",System.currentTimeMillis());v.put("revision",rev);db.update("invoice_documents",v,"id=?",new String[]{id});queue(db,"invoice_documents",id,"delete",rev);db.setTransactionSuccessful();}finally{db.endTransaction();}}
}
