package gr.mastixa.manager;

import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import java.util.*;

public final class ProductionStore {
    public record Harvest(String id,String date,String productId,String productName,String fieldId,double quantity,String notes,String windowsId) {}
    public record Sale(String id,String date,String productId,String productName,String buyerId,String buyerName,double quantity,double price,double total,String payment,String notes,String incomeWindowsId,String windowsId) {}
    static final String[] HARVEST_COLUMNS={"id","entry_date","product_id","product","field_id","quantity_kg","notes","windows_id","revision","updated_at","deleted_at"};
    static final String[] SALE_COLUMNS={"id","sale_date","product_id","product","buyer_id","buyer_name","quantity_kg","price_per_kg","total_amount","payment_method","notes","income_windows_id","windows_id","revision","updated_at","deleted_at"};
    private final FarmStore store;
    public ProductionStore(FarmStore store){this.store=store;}
    static void createTables(SQLiteDatabase db){
        db.execSQL("CREATE TABLE production(id TEXT PRIMARY KEY,entry_date TEXT NOT NULL,product_id TEXT NOT NULL,product TEXT NOT NULL,field_id TEXT NOT NULL,quantity_kg REAL NOT NULL CHECK(quantity_kg>=0),notes TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");
        db.execSQL("CREATE TABLE production_sales(id TEXT PRIMARY KEY,sale_date TEXT NOT NULL,product_id TEXT NOT NULL,product TEXT NOT NULL,buyer_id TEXT NOT NULL,buyer_name TEXT NOT NULL,quantity_kg REAL NOT NULL CHECK(quantity_kg>0),price_per_kg REAL NOT NULL CHECK(price_per_kg>=0),total_amount REAL NOT NULL CHECK(total_amount>=0),payment_method TEXT NOT NULL,notes TEXT NOT NULL,income_windows_id TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");
        db.execSQL("CREATE UNIQUE INDEX production_windows ON production(windows_id) WHERE windows_id<>''");db.execSQL("CREATE UNIQUE INDEX sales_windows ON production_sales(windows_id) WHERE windows_id<>''");db.execSQL("CREATE UNIQUE INDEX money_sale ON money_entries(source_id) WHERE kind='income' AND source_type='production_sale'");
    }
    public List<Harvest> harvests(){var result=new ArrayList<Harvest>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,entry_date,product_id,product,field_id,quantity_kg,notes,windows_id FROM production WHERE deleted_at IS NULL ORDER BY entry_date DESC,updated_at DESC,id",null)){while(c.moveToNext())result.add(new Harvest(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getDouble(5),c.getString(6),c.getString(7)));}return result;}
    public List<Sale> sales(){var result=new ArrayList<Sale>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,sale_date,product_id,product,buyer_id,buyer_name,quantity_kg,price_per_kg,total_amount,payment_method,notes,income_windows_id,windows_id FROM production_sales WHERE deleted_at IS NULL ORDER BY sale_date DESC,updated_at DESC,id",null)){while(c.moveToNext())result.add(new Sale(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getDouble(7),c.getDouble(8),c.getString(9),c.getString(10),c.getString(11),c.getString(12)));}return result;}
    public double produced(String product){return harvests().stream().filter(h->h.productId().equals(product)).mapToDouble(Harvest::quantity).sum();}
    public double sold(String product){return sales().stream().filter(s->s.productId().equals(product)).mapToDouble(Sale::quantity).sum();}
    public double available(String product){return produced(product)-sold(product);}
    static void validate(Harvest h){date(h.date());if(h.productId().isBlank()||h.productName().isBlank()||!Double.isFinite(h.quantity())||h.quantity()<0)throw new IllegalArgumentException("Μη έγκυρη παραγωγή.");}
    static void validate(Sale s){date(s.date());if(s.productId().isBlank()||s.productName().isBlank()||!Double.isFinite(s.quantity())||s.quantity()<=0||!Double.isFinite(s.price())||s.price()<0||!Double.isFinite(s.total())||s.total()<0)throw new IllegalArgumentException("Μη έγκυρη πώληση.");}
    private static void date(String value){if(value.isBlank())throw new IllegalArgumentException("Χρειάζεται ημερομηνία.");CatalogStore.validateCultivation(value,"active");}
    private void reference(String table,String id){if(id.isEmpty())return;try(var c=store.getReadableDatabase().rawQuery("SELECT 1 FROM "+table+" WHERE id=?",new String[]{id})){if(!c.moveToFirst())throw new IllegalArgumentException("Λείπει συνδεδεμένη εγγραφή: "+table);}}
    private int revision(SQLiteDatabase db,String table,String id){try(var c=db.rawQuery("SELECT revision FROM "+table+" WHERE id=? AND deleted_at IS NULL",new String[]{id})){if(!c.moveToFirst())throw new IllegalArgumentException("Η εγγραφή δεν υπάρχει.");return c.getInt(0);}}
    private void queue(SQLiteDatabase db,String table,String id,String operation,int revision,long now){var v=new ContentValues();v.put("operation_id",UUID.randomUUID().toString());v.put("entity",table);v.put("entity_id",id);v.put("operation",operation);v.put("revision",revision);v.put("created_at",now);db.insertOrThrow("pending_changes",null,v);}
    private String put(String table,String id,ContentValues row){var db=store.getWritableDatabase();int rev=id==null?1:revision(db,table,id)+1;String key=id==null?UUID.randomUUID().toString():id;long now=System.currentTimeMillis();row.put("id",key);row.put("revision",rev);row.put("updated_at",now);if(id==null)db.insertOrThrow(table,null,row);else db.update(table,row,"id=?",new String[]{id});queue(db,table,key,id==null?"create":"update",rev,now);return key;}
    public String saveHarvest(Harvest h){return saveHarvest(h,false);}
    String saveHarvest(Harvest h,boolean importing){validate(h);var db=store.getWritableDatabase();db.beginTransaction();try{
        reference("products",h.productId());reference("fields",h.fieldId());var old=h.id()==null?null:harvests().stream().filter(x->x.id().equals(h.id())).findFirst().orElseThrow();if(!importing&&(h.quantity()<=0||h.fieldId().isEmpty()||!h.windowsId().isEmpty()||(old!=null&&!old.windowsId().isEmpty())))throw new IllegalArgumentException("Χρειάζεται αγροτεμάχιο και θετική ποσότητα. Το εισαγόμενο ιστορικό δεν αλλάζει.");
        if(old!=null&&!old.productId().equals(h.productId()))throw new IllegalArgumentException("Το προϊόν υπάρχουσας παραγωγής δεν αλλάζει.");double balance=available(h.productId())-(old==null?0:old.quantity())+h.quantity();if(!Double.isFinite(balance)||balance < -0.000001)throw new IllegalArgumentException("Η αλλαγή θα άφηνε πωλήσεις χωρίς διαθέσιμη παραγωγή.");
        var v=new ContentValues();v.put("entry_date",h.date());v.put("product_id",h.productId());v.put("product",h.productName());v.put("field_id",h.fieldId());v.put("quantity_kg",h.quantity());v.put("notes",h.notes().trim());v.put("windows_id",h.windowsId());String id=put("production",h.id(),v);db.setTransactionSuccessful();return id;
    }finally{db.endTransaction();}}
    public String saveSale(Sale s){return saveSale(s,false);}
    String saveSale(Sale s,boolean importing){validate(s);var db=store.getWritableDatabase();db.beginTransaction();try{
        reference("products",s.productId());reference("business_partners",s.buyerId());var old=s.id()==null?null:sales().stream().filter(x->x.id().equals(s.id())).findFirst().orElseThrow();if(!importing&&(!s.windowsId().isEmpty()||(old!=null&&!old.windowsId().isEmpty())))throw new IllegalArgumentException("Το εισαγόμενο ιστορικό δεν αλλάζει.");if(old!=null&&!old.productId().equals(s.productId()))throw new IllegalArgumentException("Το προϊόν υπάρχουσας πώλησης δεν αλλάζει.");double balance=available(s.productId())+(old==null?0:old.quantity())-s.quantity();if(!Double.isFinite(balance)||balance < -0.000001)throw new IllegalArgumentException("Η πώληση ξεπερνά τη διαθέσιμη παραγωγή.");
        var v=new ContentValues();v.put("sale_date",s.date());v.put("product_id",s.productId());v.put("product",s.productName());v.put("buyer_id",s.buyerId());v.put("buyer_name",s.buyerName().trim());v.put("quantity_kg",s.quantity());v.put("price_per_kg",s.price());v.put("total_amount",s.total());v.put("payment_method",s.payment().trim());v.put("notes",s.notes().trim());v.put("income_windows_id",s.incomeWindowsId());v.put("windows_id",s.windowsId());String id=put("production_sales",s.id(),v);if(!importing)syncIncome(id,s,false);db.setTransactionSuccessful();return id;
    }finally{db.endTransaction();}}
    private void syncIncome(String id,Sale s,boolean deleting){var db=store.getWritableDatabase();String existing=null;try(var c=db.rawQuery("SELECT id FROM money_entries WHERE kind='income' AND source_type='production_sale' AND source_id=?",new String[]{id})){if(c.moveToFirst())existing=c.getString(0);}if(deleting){if(existing!=null)MoneyStore.remove(db,existing);return;}MoneyStore.put(db,new MoneyStore.Entry(existing,"income",s.date(),"","","Πώληση προϊόντος — "+s.productName(),s.buyerId(),s.buyerName(),s.payment(),s.total(),s.notes(),"production_sale",id,""));}
    private void remove(String table,String id){var db=store.getWritableDatabase();int rev=revision(db,table,id)+1;long now=System.currentTimeMillis();var v=new ContentValues();v.put("revision",rev);v.put("updated_at",now);v.put("deleted_at",now);db.update(table,v,"id=?",new String[]{id});queue(db,table,id,"delete",rev,now);}
    public void deleteHarvest(String id){var db=store.getWritableDatabase();db.beginTransaction();try{var h=harvests().stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();if(!h.windowsId().isEmpty()||available(h.productId())-h.quantity() < -0.000001)throw new IllegalArgumentException("Δεν διαγράφεται εισαγόμενη παραγωγή ή ποσότητα που έχει πωληθεί.");remove("production",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public void deleteSale(String id){var db=store.getWritableDatabase();db.beginTransaction();try{var s=sales().stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();if(!s.windowsId().isEmpty())throw new IllegalArgumentException("Η εισαγόμενη πώληση δεν διαγράφεται.");syncIncome(id,s,true);remove("production_sales",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
}
