package gr.mastixa.manager;

import java.util.*;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;

/** Reports reuse posted finances once. Operational costs are a separate field-cost view. */
public final class ReportStore {
    public static final Set<String> PAGES=Set.of("Αναφορές","Αναφορά Πωλήσεων & Stock","Ετήσια Αναφορά Εκμετάλλευσης","Κόστη ανά Αγροτεμάχιο","Αναφορά Αποθήκης & Αξίας Stock","Καρτέλα Αγροτεμαχίου");
    public record Filter(String from,String to,String field,String product,String buyer){public Filter{CatalogStore.validateCultivation(from,"active");CatalogStore.validateCultivation(to,"active");if(!from.isEmpty()&&!to.isEmpty()&&from.compareTo(to)>0)throw new IllegalArgumentException("Μη έγκυρο διάστημα / Invalid date range");}boolean date(String d){return (from.isEmpty()||d.compareTo(from)>=0)&&(to.isEmpty()||d.compareTo(to)<=0);}boolean field(String id){return field.isEmpty()||field.equals(id);}boolean product(String id){return product.isEmpty()||product.equals(id);}boolean buyer(String id){return buyer.isEmpty()||buyer.equals(id);}}
    public record Stock(String id,String name,String unit,double quantity,double receipts,double consumed,double average,double value,String status){}
    private final FarmStore store;private final boolean en;private final String scopeId;
    public ReportStore(FarmStore store,boolean english){this.store=store;en=english;scopeId=scopeId(store);}
    private static String scopeId(FarmStore store){String name=store.getDatabaseName();if("mastixa.db".equals(name))return "legacy";if(name!=null&&name.startsWith("farm-")&&name.endsWith(".db")&&name.length()>8)return name.substring(5,name.length()-3);return "local:"+(name==null?"unknown":name);}
    String w(String el,String english){return en?english:el;}
    static String n(double d){return BigDecimal.valueOf(d).setScale(2,java.math.RoundingMode.HALF_UP).toPlainString();}
    public List<Stock> stock(){var rows=new ArrayList<Stock>();String sql="SELECT i.id,i.name,i.unit,i.minimum_stock,COALESCE(SUM(CASE WHEN m.movement_type IN ('Παραλαβή','Διόρθωση +') THEN m.quantity ELSE -m.quantity END),0),COALESCE(SUM(CASE WHEN m.movement_type='Παραλαβή' THEN m.quantity ELSE 0 END),0),COALESCE(SUM(CASE WHEN m.movement_type='Κατανάλωση' THEN m.quantity ELSE 0 END),0),COALESCE(SUM(CASE WHEN m.movement_type='Παραλαβή' THEN m.total_cost ELSE 0 END),0),COALESCE(SUM(CASE WHEN m.movement_type='Παραλαβή' AND m.unit_price>0 THEN m.quantity ELSE 0 END),0) FROM inventory_items i LEFT JOIN inventory_movements m ON m.item_id=i.id AND m.deleted_at IS NULL WHERE i.deleted_at IS NULL GROUP BY i.id ORDER BY i.name,i.id";try(var c=store.getReadableDatabase().rawQuery(sql,null)){while(c.moveToNext()){double q=c.getDouble(4),avg=c.getDouble(8)>0?c.getDouble(7)/c.getDouble(8):0;rows.add(new Stock(c.getString(0),c.getString(1),c.getString(2),q,c.getDouble(5),c.getDouble(6),avg,Math.max(0,q)*avg,q<=0?w("Εξαντλημένο","Empty"):c.getDouble(3)>0&&q<=c.getDouble(3)?w("Χαμηλό","Low"):"OK"));}}return rows;}
    public List<String[]> report(String page,Filter f){var db=store.getWritableDatabase();db.beginTransaction();try{var result=build(page,f);db.setTransactionSuccessful();return result;}finally{db.endTransaction();}}
    private List<String[]> build(String page,Filter f){var rows=new ArrayList<String[]>();rows.add(new String[]{w("Αναφορά","Report"),en?switch(page){case "Αναφορές"->"Reports";case "Αναφορά Πωλήσεων & Stock"->"Sales & Stock";case "Ετήσια Αναφορά Εκμετάλλευσης"->"Annual Farm Report";case "Κόστη ανά Αγροτεμάχιο"->"Costs by Field";case "Καρτέλα Αγροτεμαχίου"->"Field Record";default->"Inventory & Stock Value";}:page});rows.add(new String[]{w("Διάστημα","Period"),(f.from().isEmpty()?"…":f.from())+" — "+(f.to().isEmpty()?"…":f.to())});
        if(page.equals("Αναφορά Αποθήκης & Αξίας Stock")){rows.add(new String[]{w("Βάση υπολογισμού","Basis"),w("Τρέχον απόθεμα όλων των ετών · μέση σταθμική τιμή παραλαβών όπως στα Windows. Εκτίμηση αξίας, όχι απογραφή συγκεκριμένης ημερομηνίας.","Current stock across all years; weighted receipt cost as on Windows. Estimated value, not a historical valuation.")});double total=0;for(var s:stock()){rows.add(new String[]{s.name(),n(s.quantity())+" "+s.unit()+" · "+s.status()+" · "+w("Μέση τιμή ","Average ")+n(s.average())+" € · "+w("Αξία ","Value ")+n(s.value())+" €"});rows.add(new String[]{w("Παραλαβές / Κατανάλωση","Receipts / Consumption"),n(s.receipts())+" / "+n(s.consumed())+" "+s.unit()});total+=s.value();}rows.add(new String[]{w("Συνολική εκτιμώμενη αξία","Total estimated value"),n(total)+" €"});return rows;}
        if(!f.field().isEmpty())rows.add(new String[]{w("Αγροτεμάχιο (παραγωγή / οικονομικά)","Field (production / finances)"),store.fields().stream().filter(x->x.id().equals(f.field())).map(FarmStore.Field::name).findFirst().orElse("—")});
        if(!f.product().isEmpty())rows.add(new String[]{w("Προϊόν (μόνο παραγωγή / πωλήσεις)","Product (production / sales only)"),new CatalogStore(store).products().stream().filter(x->x.id().equals(f.product())).map(CatalogStore.Product::name).findFirst().orElse("—")});
        if(!f.buyer().isEmpty())rows.add(new String[]{w("Αγοραστής (μόνο πωλήσεις)","Buyer (sales only)"),new PartnerStore(store).partners().stream().filter(x->x.id().equals(f.buyer())).map(PartnerStore.Partner::name).findFirst().orElse("—")});
        var money=new MoneyStore(store).entries(null).stream().filter(e->f.date(e.date())&&f.field(e.fieldId())).toList();double income=money.stream().filter(e->e.kind().equals("income")).mapToDouble(MoneyStore.Entry::amount).sum(),expenses=money.stream().filter(e->e.kind().equals("expense")).mapToDouble(MoneyStore.Entry::amount).sum();
        if(page.equals("Αναφορές")||page.equals("Ετήσια Αναφορά Εκμετάλλευσης")){rows.add(new String[]{w("Καταχωρημένα έσοδα","Posted income"),n(income)+" €"});rows.add(new String[]{w("Καταχωρημένα έξοδα","Posted expenses"),n(expenses)+" €"});rows.add(new String[]{w("Οικονομικό αποτέλεσμα","Financial result"),n(income-expenses)+" €"});rows.add(new String[]{w("Σημείωση","Note"),w("Οι πωλήσεις και τα αυτόματα έξοδα περιλαμβάνονται μία φορά στα οικονομικά. Κόστη καλλιέργειας εμφανίζονται χωριστά στην αναφορά αγροτεμαχίων.","Sales and automatic expenses are counted once in finances. Operational costs appear separately in the field report.")});
            var categories=new TreeMap<String,Double>();for(var e:money)categories.merge((e.kind().equals("income")?w("Έσοδα · ","Income · "):w("Έξοδα · ","Expenses · "))+e.category(),e.amount(),Double::sum);categories.forEach((k,v)->rows.add(new String[]{k,n(v)+" €"}));}
        var production=new ProductionStore(store);var harvest=production.harvests();var sales=production.sales();
        if(page.equals("Ετήσια Αναφορά Εκμετάλλευσης")||page.equals("Αναφορά Πωλήσεων & Stock")||page.equals("Αναφορές")){
            for(var p:new CatalogStore(store).products()){if(!f.product(p.id()))continue;double produced=harvest.stream().filter(h->h.productId().equals(p.id())&&f.date(h.date())&&f.field(h.fieldId())).mapToDouble(ProductionStore.Harvest::quantity).sum();var ps=sales.stream().filter(s->s.productId().equals(p.id())&&f.date(s.date())&&f.buyer(s.buyerId())).toList();double sold=ps.stream().mapToDouble(ProductionStore.Sale::quantity).sum(),value=ps.stream().mapToDouble(ProductionStore.Sale::total).sum();rows.add(new String[]{p.name(),w("Παραγωγή ","Production ")+n(produced)+" "+p.unit()+" · "+w("Πωλήσεις ","Sales ")+n(sold)+" "+p.unit()+" · "+n(value)+" €"});rows.add(new String[]{w("Τρέχον διαθέσιμο όλων των ετών","Current availability across all years"),n(production.available(p.id()))+" "+p.unit()});}
            if(page.equals("Αναφορά Πωλήσεων & Stock")){rows.add(new String[]{w("Σημείωση φίλτρων","Filter scope"),w("Οι πωλήσεις δεν συνδέονται με αγροτεμάχιο. Το διαθέσιμο αφορά όλα τα έτη και όλους τους αγοραστές.","Sales have no field allocation. Availability includes all years and buyers.")});for(var s:sales)if(f.date(s.date())&&f.product(s.productId())&&f.buyer(s.buyerId()))rows.add(new String[]{s.date()+" · "+s.productName(),s.buyerName()+" · "+n(s.quantity())+" × "+n(s.price())+" € = "+n(s.total())+" € · "+s.payment()});}}
        if(page.equals("Κόστη ανά Αγροτεμάχιο")||page.equals("Καρτέλα Αγροτεμαχίου")){
            rows.add(new String[]{w("Μέθοδος","Method"),w("Άμεσα έξοδα + καταγεγραμμένα κόστη εργασιών, φυτοπροστασίας, εργατικών και φυτεύσεων, όπως Windows. Χειροκίνητη επανάληψη ίδιου κόστους στα Έξοδα μπορεί να το μετρήσει ξανά.","Assigned expenses plus activity, protection, labor and planting costs, as on Windows. Manually duplicating an operational cost in Expenses may count it again.")});
            for(var field:store.fields()){if(!f.field(field.id()))continue;double in=money.stream().filter(e->e.fieldId().equals(field.id())&&e.kind().equals("income")).mapToDouble(MoneyStore.Entry::amount).sum(),ex=money.stream().filter(e->e.fieldId().equals(field.id())&&e.kind().equals("expense")).mapToDouble(MoneyStore.Entry::amount).sum(),operational=0;rows.add(new String[]{field.name(),n(field.area())+w(" στρ. · Δέντρα "," stremma · Trees ")+field.trees()+" · KAEK "+field.kaek()});
                for(var pair:new String[][]{{"farm_activities","activity_date"},{"plant_protection_records","application_date"},{"labor_entries","work_date"},{"planting_batches","planting_date"}}){double cost=0;try(var c=store.getReadableDatabase().rawQuery("SELECT "+pair[1]+",cost,notes FROM "+pair[0]+" WHERE field_id=? AND deleted_at IS NULL ORDER BY "+pair[1],new String[]{field.id()})){while(c.moveToNext())if(f.date(c.getString(0)))cost+=c.getDouble(1);}operational+=cost;rows.add(new String[]{label(pair[0]),n(cost)+" €"});}
                rows.add(new String[]{w("Άμεσα έξοδα / Συνολικό κόστος / Έσοδα / Αποτέλεσμα","Assigned expenses / Total cost / Income / Result"),n(ex)+" / "+n(ex+operational)+" / "+n(in)+" / "+n(in-ex-operational)+" €"});
                for(var p:new CatalogStore(store).products()){double qty=harvest.stream().filter(h->h.fieldId().equals(field.id())&&h.productId().equals(p.id())&&f.date(h.date())).mapToDouble(ProductionStore.Harvest::quantity).sum();if(qty>0)rows.add(new String[]{p.name(),n(qty)+" "+p.unit()+" · "+w("Ανά στρέμμα ","Per stremma ")+(field.area()>0?n(qty/field.area()):"—")});}
                if(page.equals("Καρτέλα Αγροτεμαχίου")){appendActivityTimeline(rows,f,field.id());for(var e:money)if(e.fieldId().equals(field.id()))rows.add(new String[]{e.date()+" · "+e.description(),(e.kind().equals("income")?w("Έσοδο","Income"):w("Έξοδο","Expense"))+" · "+n(e.amount())+" €"});}
            }
            if(f.field().isEmpty()){double unassigned=money.stream().filter(e->e.fieldId().isEmpty()&&e.kind().equals("expense")).mapToDouble(MoneyStore.Entry::amount).sum();rows.add(new String[]{w("Έξοδα χωρίς αγροτεμάχιο (δεν επιμερίζονται)","Expenses without field (not allocated)"),n(unassigned)+" €"});}
        }
        extras(rows,page,f);return rows;
    }

    private void appendActivityTimeline(List<String[]> rows,Filter f,String fieldId){int added=0;for(var event:ActivityProjection.project(store,scopeId,fieldId)){String date=event.eventDate();if(date==null){if(!f.from().isEmpty()||!f.to().isEmpty())continue;}else if(!f.date(date))continue;String when;if(event.eventAt()!=null)when=java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm 'UTC'").withZone(java.time.ZoneOffset.UTC).format(java.time.Instant.ofEpochMilli(event.eventAt()));else when=date==null?w("Άγνωστη ημερομηνία","Unknown date"):date;var detail=new ArrayList<String>();if(event.label()!=null&&!event.label().isBlank())detail.add(event.label());if(event.summary()!=null&&!event.summary().isBlank()&&!event.summary().equals(event.label()))detail.add(event.summary());if(event.status()!=null&&!event.status().equals("unknown"))detail.add(status(event.status()));if(event.timeBasis().equals("recorded"))detail.add(w("χρόνος καταγραφής","recorded time"));rows.add(new String[]{when+" · "+activityKind(event.kind()),detail.isEmpty()?"—":String.join(" · ",detail)});added++;}if(added==0)rows.add(new String[]{w("Ιστορικό δραστηριοτήτων","Activity history"),w("Δεν υπάρχουν δραστηριότητες στο επιλεγμένο διάστημα.","No activities in the selected period.")});}
    private String activityKind(String kind){return switch(kind){case "harvest"->w("Παραγωγή","Production");case "irrigation"->w("Πότισμα","Irrigation");case "fertilization"->w("Λίπανση","Fertilization");case "planting"->w("Φύτευση","Planting");case "plant_protection"->w("Φυτοπροστασία","Plant protection");case "cultivation_work"->w("Καλλιεργητική εργασία","Cultivation work");case "observation"->w("Παρατήρηση GIS","GIS observation");default->w("Δραστηριότητα","Activity");};}
    private String status(String status){return switch(status){case "planned"->w("Προγραμματισμένη","Planned");case "completed"->w("Ολοκληρώθηκε","Completed");case "cancelled"->w("Ακυρώθηκε","Cancelled");default->w("Άγνωστη κατάσταση","Unknown status");};}

    private void extras(List<String[]> rows,String page,Filter f){
        var production=new ProductionStore(store);var harvests=production.harvests();var sales=production.sales();
        if(page.equals("Αναφορές")){var years=new TreeMap<String,double[]>();for(var e:new MoneyStore(store).entries(null))if(f.date(e.date())&&f.field(e.fieldId()))years.computeIfAbsent(e.date().substring(0,4),k->new double[2])[e.kind().equals("income")?0:1]+=e.amount();for(var e:years.entrySet())rows.add(new String[]{e.getKey()+" · "+w("Έσοδα / Έξοδα / Αποτέλεσμα","Income / Expenses / Result"),n(e.getValue()[0])+" / "+n(e.getValue()[1])+" / "+n(e.getValue()[0]-e.getValue()[1])+" €"});}
        if(page.equals("Ετήσια Αναφορά Εκμετάλλευσης")||page.equals("Αναφορά Πωλήσεων & Stock")){
            for(var p:new CatalogStore(store).products()){if(!f.product(p.id()))continue;var selected=sales.stream().filter(x->x.productId().equals(p.id())&&f.date(x.date())&&f.buyer(x.buyerId())).toList();double sold=selected.stream().mapToDouble(ProductionStore.Sale::quantity).sum(),revenue=selected.stream().mapToDouble(ProductionStore.Sale::total).sum();rows.add(new String[]{p.name()+" · "+w("Πλήθος πωλήσεων / Μέση τιμή","Sales count / Average price"),selected.size()+" / "+(sold>0?n(revenue/sold):"—")+" € / "+p.unit()});
                if(!f.to().isEmpty()){double produced=harvests.stream().filter(x->x.productId().equals(p.id())&&x.date().compareTo(f.to())<=0).mapToDouble(ProductionStore.Harvest::quantity).sum(),soldTo=sales.stream().filter(x->x.productId().equals(p.id())&&x.date().compareTo(f.to())<=0).mapToDouble(ProductionStore.Sale::quantity).sum();rows.add(new String[]{p.name()+" · "+w("Απόθεμα έως ","Stock through ")+f.to(),n(Math.max(0,produced-soldTo))+" "+p.unit()+" · "+w("όλα τα αγροτεμάχια/αγοραστές","all fields/buyers")});}
                var buyers=new TreeMap<String,double[]>();for(var sale:selected){var b=buyers.computeIfAbsent(sale.buyerName(),k->new double[3]);b[0]++;b[1]+=sale.quantity();b[2]+=sale.total();}for(var b:buyers.entrySet())rows.add(new String[]{p.name()+" · "+b.getKey(),(int)b.getValue()[0]+w(" πωλήσεις · "," sales · ")+n(b.getValue()[1])+" "+p.unit()+" · "+n(b.getValue()[2])+" € · "+w("Μέση τιμή ","Average ")+(b.getValue()[1]>0?n(b.getValue()[2]/b.getValue()[1]):"—")+" € / "+p.unit()});
            }
        }
        if(page.equals("Καρτέλα Αγροτεμαχίου")){var work=new WorkStore(store);for(var field:store.fields()){if(!f.field(field.id()))continue;rows.add(new String[]{field.name(),field.location()+" · "+field.notes()});int planted=0,alive=0;for(var p:work.plantings())if(p.field_id().equals(field.id())&&f.date(p.planting_date())){planted+=p.trees_planted();alive+=p.trees_alive();}rows.add(new String[]{w("Φυτεμένα / Ζωντανά / Επιβίωση","Planted / Alive / Survival"),planted+" / "+alive+" / "+(planted>0?n(alive*100.0/planted)+"%":"—")});double hours=work.labor().stream().filter(x->x.field_id().equals(field.id())&&f.date(x.work_date())).mapToDouble(WorkStore.Labor::hours).sum();rows.add(new String[]{w("Ώρες εργατικών","Labor hours"),n(hours)});try(var c=store.getReadableDatabase().rawQuery("SELECT m.movement_date,i.name,i.unit,m.movement_type,m.quantity,m.notes FROM inventory_movements m JOIN inventory_items i ON i.id=m.item_id WHERE m.deleted_at IS NULL AND m.field_id=? ORDER BY m.movement_date",new String[]{field.id()})){while(c.moveToNext())if(f.date(c.getString(0)))rows.add(new String[]{c.getString(0)+" · "+c.getString(1),c.getString(3)+" · "+n(c.getDouble(4))+" "+c.getString(2)+" · "+c.getString(5)});}}}
    }
    private static String xml(String s){var clean=new StringBuilder();s.codePoints().filter(c->c==9||c==10||c==13||c>=32).forEach(clean::appendCodePoint);return clean.toString().replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    public static byte[] xlsx(List<String[]> rows)throws java.io.IOException{
        return xlsx(rows,"Mastixa Report",false);
    }
    static byte[] xlsx(List<String[]> rows,String sheetName,boolean coordinates)throws java.io.IOException{
        var out=new java.io.ByteArrayOutputStream();try(var zip=new java.util.zip.ZipOutputStream(out)){
            var files=new LinkedHashMap<String,String>();files.put("[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");
            files.put("_rels/.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
            files.put("xl/workbook.xml","<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\""+xml(sheetName)+"\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");
            files.put("xl/_rels/workbook.xml.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");
            var sheet=new StringBuilder("<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><cols><col min=\"1\" max=\"1\" width=\"48\" customWidth=\"1\"/><col min=\"2\" max=\"2\" width=\"110\" customWidth=\"1\"/></cols><sheetData>");int n=0;for(var row:rows){sheet.append("<row r=\"").append(++n).append("\">");for(int j=0;j<row.length;j++){sheet.append("<c r=\"").append((char)('A'+j)).append(n);if(coordinates&&n>1&&j>=4)sheet.append("\" t=\"n\"><v>").append(new java.math.BigDecimal(row[j]).toPlainString()).append("</v></c>");else sheet.append("\" t=\"inlineStr\"><is><t xml:space=\"preserve\">").append(xml(row[j])).append("</t></is></c>");}sheet.append("</row>");}sheet.append("</sheetData></worksheet>");files.put("xl/worksheets/sheet1.xml",coordinates?sheet.toString().replace("width=\"48\"","width=\"30\"").replace("max=\"2\" width=\"110\"","max=\"12\" width=\"23\""):sheet.toString());for(var e:files.entrySet()){zip.putNextEntry(new java.util.zip.ZipEntry(e.getKey()));zip.write(("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"+e.getValue()).getBytes(StandardCharsets.UTF_8));zip.closeEntry();}}
        return out.toByteArray();
    }
    private String label(String table){return switch(table){case "farm_activities"->w("Άρδευση & Λίπανση","Irrigation & Fertilization");case "plant_protection_records"->w("Φυτοπροστασία","Plant protection");case "labor_entries"->w("Εργατικά","Labor");default->w("Φυτεύσεις","Plantings");};}
    public static byte[] csv(List<String[]> rows){var out=new StringBuilder("\uFEFF");for(var row:rows){for(int i=0;i<row.length;i++){if(i>0)out.append(';');String s=row[i];if(!s.stripLeading().isEmpty()&&"=+@-".indexOf(s.stripLeading().charAt(0))>=0)s="'"+s;out.append('"').append(s.replace("\"","\"\"")).append('"');}out.append("\r\n");}return out.toString().getBytes(StandardCharsets.UTF_8);}
    public static byte[] pdf(List<String[]> rows)throws java.io.IOException{var doc=new android.graphics.pdf.PdfDocument();try(var out=new java.io.ByteArrayOutputStream()){var paint=new android.graphics.Paint(android.graphics.Paint.ANTI_ALIAS_FLAG);paint.setTextSize(11);int number=1,y=40;var page=doc.startPage(new android.graphics.pdf.PdfDocument.PageInfo.Builder(595,842,number).create());for(var row:rows){String line=String.join(" : ",row);for(String paragraph:line.split("\n",-1)){while(!paragraph.isEmpty()){int count=paint.breakText(paragraph,true,515,null);if(count<1)count=1;if(count<paragraph.length()){int space=paragraph.lastIndexOf(' ',count);if(space>0)count=space;}if(y>795){doc.finishPage(page);page=doc.startPage(new android.graphics.pdf.PdfDocument.PageInfo.Builder(595,842,++number).create());y=40;}page.getCanvas().drawText(paragraph.substring(0,count),40,y,paint);y+=16;paragraph=paragraph.substring(count).stripLeading();}y+=5;}}doc.finishPage(page);doc.writeTo(out);return out.toByteArray();}finally{doc.close();}}
}
