package gr.mastixa.manager;
import android.content.ContentValues;
import android.database.sqlite.SQLiteDatabase;
import java.util.*;

/** Plant protection and labor records. Costs stay in their source register, matching Windows. */
public final class WorkStore {
    private final FarmStore store;
    public WorkStore(FarmStore store){this.store=store;}
    public record Protection(String id,String application_date,String field_id,String inventory_item_id,String purpose,String product_name,String active_ingredient,String authorization_number,double dose,String dose_unit,double spray_volume_l,double area_stremma,String applicator,String weather,int harvest_interval_days,double cost,String notes,double inventory_quantity,String movement_id,String windows_id) {}
    static final String[] PROTECTION_COLUMNS={"id","application_date","field_id","inventory_item_id","purpose","product_name","active_ingredient","authorization_number","dose","dose_unit","spray_volume_l","area_stremma","applicator","weather","harvest_interval_days","cost","notes","inventory_quantity","movement_id","windows_id","revision","updated_at","deleted_at"};
    public List<Protection> protections(){var result=new ArrayList<Protection>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,application_date,field_id,inventory_item_id,purpose,product_name,active_ingredient,authorization_number,dose,dose_unit,spray_volume_l,area_stremma,applicator,weather,harvest_interval_days,cost,notes,inventory_quantity,movement_id,windows_id FROM plant_protection_records WHERE deleted_at IS NULL ORDER BY application_date DESC,id",null)){while(c.moveToNext())result.add(new Protection(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getString(6),c.getString(7),c.getDouble(8),c.getString(9),c.getDouble(10),c.getDouble(11),c.getString(12),c.getString(13),c.getInt(14),c.getDouble(15),c.getString(16),c.getDouble(17),c.getString(18),c.getString(19)));}return result;}
    static ContentValues values(Protection a){var v=new ContentValues();v.put("application_date",a.application_date());v.put("field_id",a.field_id());v.put("inventory_item_id",a.inventory_item_id());v.put("purpose",a.purpose());v.put("product_name",a.product_name());v.put("active_ingredient",a.active_ingredient());v.put("authorization_number",a.authorization_number());v.put("dose",a.dose());v.put("dose_unit",a.dose_unit());v.put("spray_volume_l",a.spray_volume_l());v.put("area_stremma",a.area_stremma());v.put("applicator",a.applicator());v.put("weather",a.weather());v.put("harvest_interval_days",a.harvest_interval_days());v.put("cost",a.cost());v.put("notes",a.notes());v.put("inventory_quantity",a.inventory_quantity());v.put("movement_id",a.movement_id());v.put("windows_id",a.windows_id());return v;}
    public record Worker(String id,String name,String role,String phone,double default_hourly_rate,int active,String notes,String windows_id) {}
    static final String[] WORKER_COLUMNS={"id","name","role","phone","default_hourly_rate","active","notes","windows_id","revision","updated_at","deleted_at"};
    public List<Worker> workers(){var result=new ArrayList<Worker>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,name,role,phone,default_hourly_rate,active,notes,windows_id FROM workers WHERE deleted_at IS NULL ORDER BY name,id",null)){while(c.moveToNext())result.add(new Worker(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getDouble(4),c.getInt(5),c.getString(6),c.getString(7)));}return result;}
    static ContentValues values(Worker a){var v=new ContentValues();v.put("name",a.name());v.put("role",a.role());v.put("phone",a.phone());v.put("default_hourly_rate",a.default_hourly_rate());v.put("active",a.active());v.put("notes",a.notes());v.put("windows_id",a.windows_id());return v;}
    public record Labor(String id,String work_date,String field_id,String worker_id,String work_type,double hours,double hourly_rate,double cost,String notes,String windows_id) {}
    static final String[] LABOR_COLUMNS={"id","work_date","field_id","worker_id","work_type","hours","hourly_rate","cost","notes","windows_id","revision","updated_at","deleted_at"};
    public List<Labor> labor(){var result=new ArrayList<Labor>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,work_date,field_id,worker_id,work_type,hours,hourly_rate,cost,notes,windows_id FROM labor_entries WHERE deleted_at IS NULL ORDER BY work_date DESC,id",null)){while(c.moveToNext())result.add(new Labor(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getDouble(5),c.getDouble(6),c.getDouble(7),c.getString(8),c.getString(9)));}return result;}
    static ContentValues values(Labor a){var v=new ContentValues();v.put("work_date",a.work_date());v.put("field_id",a.field_id());v.put("worker_id",a.worker_id());v.put("work_type",a.work_type());v.put("hours",a.hours());v.put("hourly_rate",a.hourly_rate());v.put("cost",a.cost());v.put("notes",a.notes());v.put("windows_id",a.windows_id());return v;}
    static void createTables(SQLiteDatabase db){db.execSQL("CREATE TABLE plant_protection_records(id TEXT PRIMARY KEY,application_date TEXT NOT NULL,field_id TEXT NOT NULL,inventory_item_id TEXT NOT NULL,purpose TEXT NOT NULL,product_name TEXT NOT NULL,active_ingredient TEXT NOT NULL,authorization_number TEXT NOT NULL,dose REAL NOT NULL CHECK(dose>=0),dose_unit TEXT NOT NULL,spray_volume_l REAL NOT NULL CHECK(spray_volume_l>=0),area_stremma REAL NOT NULL CHECK(area_stremma>=0),applicator TEXT NOT NULL,weather TEXT NOT NULL,harvest_interval_days INTEGER NOT NULL CHECK(harvest_interval_days>=0),cost REAL NOT NULL CHECK(cost>=0),notes TEXT NOT NULL,inventory_quantity REAL NOT NULL CHECK(inventory_quantity>=0),movement_id TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX plant_protection_records_windows ON plant_protection_records(windows_id) WHERE windows_id<>''");db.execSQL("CREATE TABLE workers(id TEXT PRIMARY KEY,name TEXT NOT NULL,role TEXT NOT NULL,phone TEXT NOT NULL,default_hourly_rate REAL NOT NULL CHECK(default_hourly_rate>=0),active INTEGER NOT NULL CHECK(active IN (0,1)),notes TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX workers_windows ON workers(windows_id) WHERE windows_id<>''");db.execSQL("CREATE TABLE labor_entries(id TEXT PRIMARY KEY,work_date TEXT NOT NULL,field_id TEXT NOT NULL,worker_id TEXT NOT NULL,work_type TEXT NOT NULL,hours REAL NOT NULL CHECK(hours>=0),hourly_rate REAL NOT NULL CHECK(hourly_rate>=0),cost REAL NOT NULL CHECK(cost>=0),notes TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX labor_entries_windows ON labor_entries(windows_id) WHERE windows_id<>''");}
    static void number(double... values){for(double value:values)if(!Double.isFinite(value)||value<0)throw new IllegalArgumentException("Χρειάζονται μη αρνητικοί αριθμοί.");}
    static void date(String value){if(value.isBlank())throw new IllegalArgumentException("Χρειάζεται ημερομηνία.");CatalogStore.validateCultivation(value,"active");}
    static void validate(Protection a){date(a.application_date());number(a.dose(),a.spray_volume_l(),a.area_stremma(),a.harvest_interval_days(),a.cost(),a.inventory_quantity());if(a.field_id().isBlank()||a.purpose().isBlank()||a.product_name().isBlank()||(a.inventory_quantity()>0&&a.inventory_item_id().isBlank()))throw new IllegalArgumentException("Συμπλήρωσε αγροτεμάχιο, στόχο, προϊόν και είδος αποθήκης όταν υπάρχει κατανάλωση.");}
    static void validate(Worker a){number(a.default_hourly_rate());if(a.name().isBlank()||(a.active()!=0&&a.active()!=1))throw new IllegalArgumentException("Χρειάζεται ονοματεπώνυμο και έγκυρη κατάσταση εργαζομένου.");}
    static void validate(Labor a){date(a.work_date());number(a.hours(),a.hourly_rate(),a.cost());if(a.worker_id().isBlank()||a.work_type().isBlank()||a.hours()<=0)throw new IllegalArgumentException("Συμπλήρωσε εργαζόμενο, εργασία και θετικές ώρες.");}
    private void reference(String table,String id){if(id.isEmpty())return;try(var c=store.getReadableDatabase().rawQuery("SELECT 1 FROM "+table+" WHERE id=?",new String[]{id})){if(!c.moveToFirst())throw new IllegalArgumentException("Λείπει συνδεδεμένη εγγραφή: "+table);}}
    private int revision(String table,String id){try(var c=store.getReadableDatabase().rawQuery("SELECT revision FROM "+table+" WHERE id=? AND deleted_at IS NULL",new String[]{id})){if(!c.moveToFirst())throw new IllegalArgumentException("Η εγγραφή δεν υπάρχει.");return c.getInt(0);}}
    private void queue(String table,String id,String operation,int revision,long now){var v=new ContentValues();v.put("operation_id",UUID.randomUUID().toString());v.put("entity",table);v.put("entity_id",id);v.put("operation",operation);v.put("revision",revision);v.put("created_at",now);store.getWritableDatabase().insertOrThrow("pending_changes",null,v);}
    private String put(String table,String id,ContentValues row){boolean fresh=id==null;int rev=fresh?1:revision(table,id)+1;String key=fresh?UUID.randomUUID().toString():id;long now=System.currentTimeMillis();row.put("id",key);row.put("revision",rev);row.put("updated_at",now);if(fresh)store.getWritableDatabase().insertOrThrow(table,null,row);else store.getWritableDatabase().update(table,row,"id=?",new String[]{key});queue(table,key,fresh?"create":"update",rev,now);return key;}
    private void remove(String table,String id){int rev=revision(table,id)+1;long now=System.currentTimeMillis();var row=new ContentValues();row.put("revision",rev);row.put("updated_at",now);row.put("deleted_at",now);store.getWritableDatabase().update(table,row,"id=?",new String[]{id});queue(table,id,"delete",rev,now);}
    private void editable(String table,String id,String windows,boolean importing){if(importing)return;if(!windows.isEmpty())throw new IllegalArgumentException("Το εισαγόμενο ιστορικό δεν αλλάζει.");if(id!=null)try(var c=store.getReadableDatabase().rawQuery("SELECT windows_id FROM "+table+" WHERE id=? AND deleted_at IS NULL",new String[]{id})){if(!c.moveToFirst()||!c.getString(0).isEmpty())throw new IllegalArgumentException("Το εισαγόμενο ιστορικό δεν αλλάζει.");}}
    public String saveProtection(Protection a){return saveProtection(a,false);}
    String saveProtection(Protection a,boolean importing){validate(a);var db=store.getWritableDatabase();db.beginTransaction();try{
        editable("plant_protection_records",a.id(),a.windows_id(),importing);reference("fields",a.field_id());reference("inventory_items",a.inventory_item_id());var row=values(a);
        // Insert/update the owner first; the outer transaction also rolls back its queue if consumption fails.
        String id=put("plant_protection_records",a.id(),row);
        if(!importing){String movement=new InventoryStore(store).syncProtectionConsumption(id,a);var link=new ContentValues();link.put("movement_id",movement);db.update("plant_protection_records",link,"id=?",new String[]{id});}else reference("inventory_movements",a.movement_id());
        db.setTransactionSuccessful();return id;
    }finally{db.endTransaction();}}
    public String saveWorker(Worker a){return saveWorker(a,false);}
    String saveWorker(Worker a,boolean importing){validate(a);var db=store.getWritableDatabase();db.beginTransaction();try{editable("workers",a.id(),a.windows_id(),importing);if(workers().stream().anyMatch(w->!w.id().equals(a.id())&&w.name().equalsIgnoreCase(a.name().trim())))throw new IllegalArgumentException("Υπάρχει εργαζόμενος με αυτό το όνομα.");var row=values(a);row.put("name",a.name().trim());String id=put("workers",a.id(),row);db.setTransactionSuccessful();return id;}finally{db.endTransaction();}}
    public String saveLabor(Labor a){return saveLabor(a,false);}
    String saveLabor(Labor a,boolean importing){validate(a);var db=store.getWritableDatabase();db.beginTransaction();try{editable("labor_entries",a.id(),a.windows_id(),importing);reference("fields",a.field_id());reference("workers",a.worker_id());if(!importing){var worker=workers().stream().filter(w->w.id().equals(a.worker_id())).findFirst().orElseThrow(()->new IllegalArgumentException("Ο εργαζόμενος έχει διαγραφεί."));if(worker.active()==0&&(a.id()==null||labor().stream().noneMatch(l->l.id().equals(a.id())&&l.worker_id().equals(a.worker_id()))))throw new IllegalArgumentException("Επίλεξε ενεργό εργαζόμενο.");}var row=values(a);if(!importing){double cost=a.hours()*a.hourly_rate();number(cost);row.put("cost",cost);}String id=put("labor_entries",a.id(),row);db.setTransactionSuccessful();return id;}finally{db.endTransaction();}}
    public void deleteProtection(String id){var db=store.getWritableDatabase();db.beginTransaction();try{editable("plant_protection_records",id,"",false);new InventoryStore(store).removeProtectionConsumption(id);remove("plant_protection_records",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public void deleteLabor(String id){var db=store.getWritableDatabase();db.beginTransaction();try{editable("labor_entries",id,"",false);remove("labor_entries",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public void deleteWorker(String id){var db=store.getWritableDatabase();db.beginTransaction();try{editable("workers",id,"",false);try(var c=db.rawQuery("SELECT 1 FROM labor_entries WHERE worker_id=? LIMIT 1",new String[]{id})){if(c.moveToFirst())throw new IllegalArgumentException("Υπάρχει ιστορικό εργατικών. Κάνε τον εργαζόμενο ανενεργό.");}remove("workers",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public record Planting(String id,String planting_date,String field_id,int trees_planted,int trees_alive,String material_type,String source,String variety,String spacing,double cost,String notes,String windows_id) {}
    static final String[] PLANTING_COLUMNS={"id","planting_date","field_id","trees_planted","trees_alive","material_type","source","variety","spacing","cost","notes","windows_id","revision","updated_at","deleted_at"};
    static void createPlantings(SQLiteDatabase db){db.execSQL("CREATE TABLE planting_batches(id TEXT PRIMARY KEY,planting_date TEXT NOT NULL,field_id TEXT NOT NULL,trees_planted INTEGER NOT NULL CHECK(trees_planted>=0),trees_alive INTEGER NOT NULL CHECK(trees_alive>=0),material_type TEXT NOT NULL,source TEXT NOT NULL,variety TEXT NOT NULL,spacing TEXT NOT NULL,cost REAL NOT NULL CHECK(cost>=0),notes TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX planting_windows ON planting_batches(windows_id) WHERE windows_id<>''");}
    public List<Planting> plantings(){var result=new ArrayList<Planting>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,planting_date,field_id,trees_planted,trees_alive,material_type,source,variety,spacing,cost,notes,windows_id FROM planting_batches WHERE deleted_at IS NULL ORDER BY planting_date DESC,id",null)){while(c.moveToNext())result.add(new Planting(c.getString(0),c.getString(1),c.getString(2),c.getInt(3),c.getInt(4),c.getString(5),c.getString(6),c.getString(7),c.getString(8),c.getDouble(9),c.getString(10),c.getString(11)));}return result;}
    static void validate(Planting a){date(a.planting_date());number(a.cost(),a.trees_planted(),a.trees_alive());if(a.field_id().isBlank()||a.trees_alive()>a.trees_planted())throw new IllegalArgumentException("Επίλεξε αγροτεμάχιο. Τα ζωντανά δέντρα δεν μπορούν να ξεπερνούν τα φυτεμένα.");}
    public String savePlanting(Planting a){return savePlanting(a,false);}
    String savePlanting(Planting a,boolean importing){validate(a);var db=store.getWritableDatabase();db.beginTransaction();try{editable("planting_batches",a.id(),a.windows_id(),importing);reference("fields",a.field_id());var v=new ContentValues();v.put("planting_date",a.planting_date());v.put("field_id",a.field_id());v.put("trees_planted",a.trees_planted());v.put("trees_alive",a.trees_alive());v.put("material_type",a.material_type());v.put("source",a.source());v.put("variety",a.variety());v.put("spacing",a.spacing());v.put("cost",a.cost());v.put("notes",a.notes());v.put("windows_id",a.windows_id());String id=put("planting_batches",a.id(),v);db.setTransactionSuccessful();return id;}finally{db.endTransaction();}}
    public void deletePlanting(String id){var db=store.getWritableDatabase();db.beginTransaction();try{editable("planting_batches",id,"",false);remove("planting_batches",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public record Equipment(String id,String name,String category,String brand_model,String equipment_code,String purchase_date,String fuel,String meter_type,double current_meter,String status,String notes,String windows_id) {}
    static final String[] EQUIPMENT_COLUMNS={"id","name","category","brand_model","equipment_code","purchase_date","fuel","meter_type","current_meter","status","notes","windows_id","revision","updated_at","deleted_at"};
    public List<Equipment> equipment(){var result=new ArrayList<Equipment>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,name,category,brand_model,equipment_code,purchase_date,fuel,meter_type,current_meter,status,notes,windows_id FROM equipment WHERE deleted_at IS NULL ORDER BY name,updated_at DESC,id",null)){while(c.moveToNext())result.add(new Equipment(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getString(6),c.getString(7),c.getDouble(8),c.getString(9),c.getString(10),c.getString(11)));}return result;}
    static ContentValues values(Equipment a){var v=new ContentValues();v.put("name",a.name());v.put("category",a.category());v.put("brand_model",a.brand_model());v.put("equipment_code",a.equipment_code());v.put("purchase_date",a.purchase_date());v.put("fuel",a.fuel());v.put("meter_type",a.meter_type());v.put("current_meter",a.current_meter());v.put("status",a.status());v.put("notes",a.notes());v.put("windows_id",a.windows_id());return v;}
    public record Service(String id,String equipment_id,String service_date,String service_type,double cost,double meter_value,String technician,String notes,String next_service_date,Double next_service_meter,String expense_windows_id,String windows_id) {}
    static final String[] SERVICE_COLUMNS={"id","equipment_id","service_date","service_type","cost","meter_value","technician","notes","next_service_date","next_service_meter","expense_windows_id","windows_id","revision","updated_at","deleted_at"};
    public List<Service> services(){var result=new ArrayList<Service>();try(var c=store.getReadableDatabase().rawQuery("SELECT id,equipment_id,service_date,service_type,cost,meter_value,technician,notes,next_service_date,next_service_meter,expense_windows_id,windows_id FROM equipment_maintenance WHERE deleted_at IS NULL ORDER BY service_date DESC,updated_at DESC,id",null)){while(c.moveToNext())result.add(new Service(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getDouble(4),c.getDouble(5),c.getString(6),c.getString(7),c.getString(8),c.isNull(9)?null:c.getDouble(9),c.getString(10),c.getString(11)));}return result;}
    static ContentValues values(Service a){var v=new ContentValues();v.put("equipment_id",a.equipment_id());v.put("service_date",a.service_date());v.put("service_type",a.service_type());v.put("cost",a.cost());v.put("meter_value",a.meter_value());v.put("technician",a.technician());v.put("notes",a.notes());v.put("next_service_date",a.next_service_date());v.put("next_service_meter",a.next_service_meter());v.put("expense_windows_id",a.expense_windows_id());v.put("windows_id",a.windows_id());return v;}
    static void createEquipment(SQLiteDatabase db){db.execSQL("CREATE TABLE equipment(id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,brand_model TEXT NOT NULL,equipment_code TEXT NOT NULL,purchase_date TEXT NOT NULL,fuel TEXT NOT NULL,meter_type TEXT NOT NULL,current_meter REAL NOT NULL CHECK(current_meter>=0),status TEXT NOT NULL,notes TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX equipment_windows ON equipment(windows_id) WHERE windows_id<>''");db.execSQL("CREATE TABLE equipment_maintenance(id TEXT PRIMARY KEY,equipment_id TEXT NOT NULL,service_date TEXT NOT NULL,service_type TEXT NOT NULL,cost REAL NOT NULL CHECK(cost>=0),meter_value REAL NOT NULL CHECK(meter_value>=0),technician TEXT NOT NULL,notes TEXT NOT NULL,next_service_date TEXT NOT NULL,next_service_meter REAL CHECK(next_service_meter>=0),expense_windows_id TEXT NOT NULL,windows_id TEXT NOT NULL,revision INTEGER NOT NULL,updated_at INTEGER NOT NULL,deleted_at INTEGER)");db.execSQL("CREATE UNIQUE INDEX equipment_maintenance_windows ON equipment_maintenance(windows_id) WHERE windows_id<>''");db.execSQL("CREATE UNIQUE INDEX money_service ON money_entries(source_id) WHERE kind='expense' AND source_type='equipment_maintenance'");}
    public static final List<String> EQUIPMENT_STATUSES=List.of("Ενεργό","Σε συντήρηση","Εκτός λειτουργίας","Πωλήθηκε");
    public static final List<String> METERS=List.of("hours","km","none");
    static void validate(Equipment a){number(a.current_meter());if(a.name().isBlank()||!METERS.contains(a.meter_type())||!EQUIPMENT_STATUSES.contains(a.status()))throw new IllegalArgumentException("Συμπλήρωσε όνομα, τύπο μετρητή και κατάσταση.");if(!a.purchase_date().isEmpty())date(a.purchase_date());}
    static void validate(Service a){date(a.service_date());if(!a.next_service_date().isEmpty())date(a.next_service_date());number(a.cost(),a.meter_value());if(a.next_service_meter()!=null)number(a.next_service_meter());if(a.equipment_id().isBlank()||a.service_type().isBlank())throw new IllegalArgumentException("Επίλεξε μηχάνημα και είδος service.");}
    public String saveEquipment(Equipment a){return saveEquipment(a,false);}
    String saveEquipment(Equipment a,boolean importing){validate(a);var db=store.getWritableDatabase();db.beginTransaction();try{editable("equipment",a.id(),a.windows_id(),importing);if(a.id()!=null&&!importing){var old=equipment().stream().filter(x->x.id().equals(a.id())).findFirst().orElseThrow();if(!old.meter_type().equals(a.meter_type()))try(var c=db.rawQuery("SELECT 1 FROM equipment_maintenance WHERE equipment_id=? LIMIT 1",new String[]{a.id()})){if(c.moveToFirst())throw new IllegalArgumentException("Η μονάδα μετρητή δεν αλλάζει όταν υπάρχει ιστορικό service.");}}String id=put("equipment",a.id(),values(a));db.setTransactionSuccessful();return id;}finally{db.endTransaction();}}
    public String saveService(Service a){return saveService(a,false);}
    String saveService(Service a,boolean importing){validate(a);var db=store.getWritableDatabase();db.beginTransaction();try{editable("equipment_maintenance",a.id(),a.windows_id(),importing);reference("equipment",a.equipment_id());var equipment=equipment().stream().filter(e->e.id().equals(a.equipment_id())).findFirst().orElseThrow(()->new IllegalArgumentException("Το μηχάνημα έχει διαγραφεί."));String id=put("equipment_maintenance",a.id(),values(a));if(!importing){syncServiceExpense(id,a,equipment.name(),false);if(a.meter_value()>equipment.current_meter()){var row=values(equipment);row.put("current_meter",a.meter_value());put("equipment",equipment.id(),row);}}db.setTransactionSuccessful();return id;}finally{db.endTransaction();}}
    private void syncServiceExpense(String id,Service a,String name,boolean deleting){var db=store.getWritableDatabase();String existing=null;try(var c=db.rawQuery("SELECT id FROM money_entries WHERE kind='expense' AND source_type='equipment_maintenance' AND source_id=?",new String[]{id})){if(c.moveToFirst())existing=c.getString(0);}if(deleting||a.cost()<=0){if(existing!=null)MoneyStore.remove(db,existing);return;}MoneyStore.put(db,new MoneyStore.Entry(existing,"expense",a.service_date(),"","Μηχανήματα & Συντήρηση",a.service_type()+" — "+name,"",a.technician(),"",a.cost(),a.notes(),"equipment_maintenance",id,""));}
    public void deleteService(String id){var db=store.getWritableDatabase();db.beginTransaction();try{editable("equipment_maintenance",id,"",false);var a=services().stream().filter(x->x.id().equals(id)).findFirst().orElseThrow();syncServiceExpense(id,a,"",true);remove("equipment_maintenance",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    public void deleteEquipment(String id){var db=store.getWritableDatabase();db.beginTransaction();try{editable("equipment",id,"",false);if(services().stream().anyMatch(a->a.equipment_id().equals(id)))throw new IllegalArgumentException("Το μηχάνημα έχει συντηρήσεις. Διέγραψε πρώτα τις σχετικές εγγραφές.");remove("equipment",id);db.setTransactionSuccessful();}finally{db.endTransaction();}}
    /** Latest reminder-bearing service, matching Windows. Meter thresholds are independent of date. */
    public String reminder(Equipment e,java.time.LocalDate today){var a=services().stream().filter(x->x.equipment_id().equals(e.id())&&(!x.next_service_date().isEmpty()||x.next_service_meter()!=null)).findFirst().orElse(null);if(a==null)return "none";var due=a.next_service_date().isEmpty()?null:java.time.LocalDate.parse(a.next_service_date());if((due!=null&&due.isBefore(today))||(a.next_service_meter()!=null&&e.current_meter()>=a.next_service_meter()))return "overdue";if((due!=null&&!due.isAfter(today.plusDays(30)))||(a.next_service_meter()!=null&&a.next_service_meter()-e.current_meter()<=50))return "upcoming";return "planned";}
}
